/* ============================================================================
 *  现实资产池（商城 · 每日随机刷新）
 *  ---------------------------------------------------------------------------
 *  结构：ASSET_POOL = { car:[...], house:[...], luxury:[...] }
 *  每件：{ name, brand, category, price }  —— price 为市场价（人民币）
 *  系统价在刷新时按 0.4~0.8 随机折扣折算：systemPrice = price * discount / 1000（淫欲值）
 *  ---------------------------------------------------------------------------
 *  刷新规则：每日自动 5 车 + 3 奢侈品 + 5 房；手动刷新 20 淫欲值/次；
 *           未购买的资产不会重复出现（每类独立去重，直到买完）。
 * ==========================================================================*/
const ASSET_POOL = {
  /* ==================== 汽车（150 辆，市场价 50 万起） ==================== */
  car: [
    /* —— 豪华轿车 —— */
    { name:"宝马 530Li 尊享型 M运动套装",      brand:"宝马",   category:"轿车", price:520000 },
    { name:"宝马 540Li xDrive",                brand:"宝马",   category:"轿车", price:660000 },
    { name:"宝马 740Li 尊享型 M运动套装",      brand:"宝马",   category:"轿车", price:1260000 },
    { name:"宝马 M760Li xDrive V12",           brand:"宝马",   category:"轿车", price:2420000 },
    { name:"奔驰 E300L 豪华型",                brand:"奔驰",   category:"轿车", price:552000 },
    { name:"奔驰 S450L 4MATIC",                brand:"奔驰",   category:"轿车", price:1280000 },
    { name:"奔驰 S500L 4MATIC",                brand:"奔驰",   category:"轿车", price:1880000 },
    { name:"奔驰 AMG S63 L 4MATIC+",           brand:"奔驰",   category:"轿车", price:2830000 },
    { name:"奥迪 A6L 55 TFSI quattro 旗舰型",  brand:"奥迪",   category:"轿车", price:668000 },
    { name:"奥迪 A8L 55 TFSI quattro 旗舰型",  brand:"奥迪",   category:"轿车", price:1280000 },
    { name:"奥迪 RS7 Sportback",               brand:"奥迪",   category:"轿车", price:1460000 },
    { name:"保时捷 Panamera 4",                brand:"保时捷", category:"轿车", price:1198000 },
    { name:"保时捷 Panamera Turbo S",          brand:"保时捷", category:"轿车", price:2470000 },
    { name:"迈巴赫 S480 4MATIC",               brand:"迈巴赫", category:"轿车", price:1468000 },
    { name:"迈巴赫 S680 4MATIC",               brand:"迈巴赫", category:"轿车", price:3290000 },
    { name:"宾利飞驰 V8",                      brand:"宾利",   category:"轿车", price:2740000 },
    { name:"宾利慕尚 6.75T",                   brand:"宾利",   category:"轿车", price:4650000 },
    { name:"劳斯莱斯古思特",                   brand:"劳斯莱斯",category:"轿车", price:5030000 },
    { name:"劳斯莱斯幻影标准版",               brand:"劳斯莱斯",category:"轿车", price:8470000 },
    { name:"雷克萨斯 LS500h 行政版",           brand:"雷克萨斯",category:"轿车", price:1110000 },
    { name:"沃尔沃 S90 B5 智雅豪华版",         brand:"沃尔沃", category:"轿车", price:508000 },
    { name:"红旗 H9 3.0T 智联旗领版",          brand:"红旗",   category:"轿车", price:539800 },

    /* —— 跑车 —— */
    { name:"保时捷 718 Boxster GTS 2.5T",      brand:"保时捷", category:"跑车", price:878000 },
    { name:"保时捷 911 Carrera 3.0T",          brand:"保时捷", category:"跑车", price:1399000 },
    { name:"保时捷 911 Turbo S 3.7T",          brand:"保时捷", category:"跑车", price:2330000 },
    { name:"保时捷 Taycan Turbo S",            brand:"保时捷", category:"跑车", price:1818000 },
    { name:"奔驰 AMG GT 53 4MATIC+",           brand:"奔驰",   category:"跑车", price:1310000 },
    { name:"宝马 M4 雷霆版",                   brand:"宝马",   category:"跑车", price:950000 },
    { name:"宝马 M8 雷霆版",                   brand:"宝马",   category:"跑车", price:2200000 },
    { name:"奥迪 R8 V10 performance",          brand:"奥迪",   category:"跑车", price:2320000 },
    { name:"法拉利 Roma 3.9T",                 brand:"法拉利", category:"跑车", price:2762000 },
    { name:"法拉利 296 GTB",                   brand:"法拉利", category:"跑车", price:2980000 },
    { name:"法拉利 SF90 Stradale",             brand:"法拉利", category:"跑车", price:4880000 },
    { name:"兰博基尼 Huracán EVO",             brand:"兰博基尼",category:"跑车", price:3210000 },
    { name:"兰博基尼 Revuelto",                brand:"兰博基尼",category:"跑车", price:6290000 },
    { name:"迈凯伦 720S Spider",               brand:"迈凯伦", category:"跑车", price:3780000 },
    { name:"阿斯顿马丁 DB11 V8",               brand:"阿斯顿马丁",category:"跑车", price:2350000 },
    { name:"阿斯顿马丁 DBS Superleggera",      brand:"阿斯顿马丁",category:"跑车", price:3780000 },
    { name:"日产 GT-R R35 尊享版",             brand:"日产",   category:"跑车", price:1620000 },
    { name:"丰田 世纪 GRMN",                   brand:"丰田",   category:"跑车", price:2000000 },
    { name:"路特斯 Emira V6",                  brand:"路特斯", category:"跑车", price:1120000 },
    { name:"捷豹 F-TYPE R 5.0T",               brand:"捷豹",   category:"跑车", price:1300000 },

    /* —— 豪华 SUV —— */
    { name:"宝马 X5 xDrive40Li 尊享型",        brand:"宝马",   category:"SUV", price:800000 },
    { name:"宝马 X7 xDrive40i 尊享型",         brand:"宝马",   category:"SUV", price:1100000 },
    { name:"宝马 XM",                          brand:"宝马",   category:"SUV", price:2300000 },
    { name:"奔驰 GLE450 4MATIC 豪华型",        brand:"奔驰",   category:"SUV", price:880000 },
    { name:"奔驰 GLS450 4MATIC 豪华型",        brand:"奔驰",   category:"SUV", price:1300000 },
    { name:"奔驰 G500 时光铭刻特别版",         brand:"奔驰",   category:"SUV", price:2000000 },
    { name:"奔驰 AMG G63",                     brand:"奔驰",   category:"SUV", price:2800000 },
    { name:"奥迪 Q7 55 TFSI quattro 尊贵型",   brand:"奥迪",   category:"SUV", price:800000 },
    { name:"奥迪 Q8 55 TFSI quattro 尊享型",   brand:"奥迪",   category:"SUV", price:1100000 },
    { name:"保时捷 Macan Turbo",               brand:"保时捷", category:"SUV", price:950000 },
    { name:"保时捷 Cayenne Turbo GT",          brand:"保时捷", category:"SUV", price:2440000 },
    { name:"路虎揽胜 3.0T L6 盛世版",          brand:"路虎",   category:"SUV", price:1460000 },
    { name:"路虎揽胜 4.4T V8 巅峰创世版",      brand:"路虎",   category:"SUV", price:3300000 },
    { name:"路虎卫士 110 3.0T 大都会版",       brand:"路虎",   category:"SUV", price:1180000 },
    { name:"玛莎拉蒂 Levante Trofeo",          brand:"玛莎拉蒂",category:"SUV", price:1810000 },
    { name:"宾利添越 V8",                      brand:"宾利",   category:"SUV", price:2690000 },
    { name:"劳斯莱斯库里南",                   brand:"劳斯莱斯",category:"SUV", price:6910000 },
    { name:"雷克萨斯 LX600 巅峰版",            brand:"雷克萨斯",category:"SUV", price:1560000 },
    { name:"林肯领航员 3.5T 总统版",           brand:"林肯",   category:"SUV", price:1290000 },
    { name:"凯迪拉克 凯雷德 6.2L 铂金版",      brand:"凯迪拉克",category:"SUV", price:1600000 },
    { name:"沃尔沃 XC90 B6 智雅豪华版",        brand:"沃尔沃", category:"SUV", price:696000 },
    { name:"大众途锐 3.0T 锐尊版",             brand:"大众",   category:"SUV", price:770000 },
    { name:"丰田兰德酷路泽 4.0L 高配",         brand:"丰田",   category:"SUV", price:1100000 },

    /* —— 新能源旗舰 —— */
    { name:"蔚来 ES8 签名版 100kWh",           brand:"蔚来",   category:"新能源", price:596000 },
    { name:"蔚来 ET7 首发版 100kWh",           brand:"蔚来",   category:"新能源", price:529000 },
    { name:"理想 L9 Max",                      brand:"理想",   category:"新能源", price:459800 },
    { name:"理想 MEGA",                        brand:"理想",   category:"新能源", price:559800 },
    { name:"极氪 009 光辉版",                  brand:"极氪",   category:"新能源", price:789000 },
    { name:"极氪 001 FR",                      brand:"极氪",   category:"新能源", price:769000 },
    { name:"问界 M9 增程版 顶配",              brand:"问界",   category:"新能源", price:599800 },
    { name:"阿维塔 12 四驱 顶配",              brand:"阿维塔", category:"新能源", price:449900 },
    { name:"高合 HiPhi X 旗舰版 6座",          brand:"高合",   category:"新能源", price:800000 },
    { name:"高合 HiPhi Z 旗舰版",              brand:"高合",   category:"新能源", price:610000 },
    { name:"智己 L7 顶配",                     brand:"智己",   category:"新能源", price:579000 },
    { name:"仰望 U8 豪华版",                   brand:"仰望",   category:"新能源", price:1098000 },
    { name:"仰望 U9",                          brand:"仰望",   category:"新能源", price:1680000 },
    { name:"比亚迪 腾势 D9 创始版",            brand:"腾势",   category:"新能源", price:669000 },
    { name:"比亚迪 汉 L 四驱旗舰",             brand:"比亚迪", category:"新能源", price:329800 },
    { name:"特斯拉 Model S Plaid",             brand:"特斯拉", category:"新能源", price:1050000 },
    { name:"特斯拉 Model X Plaid",             brand:"特斯拉", category:"新能源", price:1130000 },
    { name:"保时捷 Taycan 4S",                 brand:"保时捷", category:"新能源", price:1300000 },
    { name:"奔驰 EQS 580 4MATIC",              brand:"奔驰",   category:"新能源", price:1330000 },
    { name:"宝马 i7 xDrive60L 尊享型",         brand:"宝马",   category:"新能源", price:1450000 },
    { name:"奥迪 e-tron GT quattro",           brand:"奥迪",   category:"新能源", price:1680000 },
    { name:"路特斯 Eletre R+",                 brand:"路特斯", category:"新能源", price:1320000 },
    { name:"劳斯莱斯 闪灵",                    brand:"劳斯莱斯",category:"新能源", price:5750000 },

    /* —— MPV —— */
    { name:"丰田埃尔法 尊贵版",                brand:"丰田",   category:"MPV", price:920000 },
    { name:"雷克萨斯 LM 350h 七座隽雅版",      brand:"雷克萨斯",category:"MPV", price:1199000 },
    { name:"奔驰 V260L 尊贵加长版",            brand:"奔驰",   category:"MPV", price:650000 },
    { name:"别克世纪 CENTURY 四座私享版",      brand:"别克",   category:"MPV", price:689000 },
    { name:"岚图梦想家 私人定制版",            brand:"岚图",   category:"MPV", price:639900 },
    /* —— 顶级超跑（天花板） —— */
    { name:"帕加尼 Huayra BC",                 brand:"帕加尼", category:"顶级超跑", price:28000000 },
    { name:"帕加尼 Utopia",                    brand:"帕加尼", category:"顶级超跑", price:31000000 },
    { name:"布加迪 Chiron Super Sport 300+",   brand:"布加迪", category:"顶级超跑", price:44000000 },
    { name:"布加迪 Mistral W16",               brand:"布加迪", category:"顶级超跑", price:44000000 },
    { name:"柯尼塞格 Jesko Absolut",           brand:"柯尼塞格",category:"顶级超跑", price:38000000 },
    { name:"柯尼塞格 Gemera",                  brand:"柯尼塞格",category:"顶级超跑", price:28000000 },
    { name:"迈凯伦 Speedtail",                 brand:"迈凯伦", category:"顶级超跑", price:25000000 },
    { name:"迈凯伦 P1",                        brand:"迈凯伦", category:"顶级超跑", price:16800000 },
    { name:"法拉利 LaFerrari",                 brand:"法拉利", category:"顶级超跑", price:22500000 },
    { name:"法拉利 FXX-K",                     brand:"法拉利", category:"顶级超跑", price:33000000 },
    { name:"兰博基尼 Veneno",                  brand:"兰博基尼",category:"顶级超跑", price:60000000 },
    { name:"兰博基尼 Centenario",              brand:"兰博基尼",category:"顶级超跑", price:28000000 },
    { name:"保时捷 918 Spyder",                brand:"保时捷", category:"顶级超跑", price:15000000 },
    { name:"阿斯顿马丁 Valkyrie",              brand:"阿斯顿马丁",category:"顶级超跑", price:32000000 },
    { name:"梅赛德斯-AMG ONE",                 brand:"奔驰",   category:"顶级超跑", price:28000000 },
    { name:"布加迪 Veyron 16.4 Grand Sport",   brand:"布加迪", category:"顶级超跑", price:26000000 },
    { name:"轩尼诗 Venom F5",                  brand:"轩尼诗", category:"顶级超跑", price:29000000 },
    { name:"西尔贝 SSC Tuatara",               brand:"西尔贝", category:"顶级超跑", price:26000000 },
    { name:"玛莎拉蒂 MC12",                    brand:"玛莎拉蒂",category:"顶级超跑", price:30000000 },
    { name:"劳斯莱斯 逐影（Sweptail）",        brand:"劳斯莱斯",category:"顶级超跑", price:100000000 },
    { name:"路特斯 Evija",                     brand:"路特斯", category:"顶级超跑", price:26000000 },
    { name:"Apollo Intensa Emozione",          brand:"Apollo", category:"顶级超跑", price:29000000 },

    /* —— 第二批：更多豪华/运动/旗舰 —— */
    { name:"奔驰 AMG A45 S 4MATIC+",           brand:"奔驰",   category:"性能车", price:585000 },
    { name:"奔驰 AMG CLA45 S 4MATIC+",         brand:"奔驰",   category:"性能车", price:635000 },
    { name:"奔驰 AMG E53 4MATIC+ 轿跑",        brand:"奔驰",   category:"性能车", price:1010000 },
    { name:"奔驰 AMG GT 63 S 4MATIC+",         brand:"奔驰",   category:"性能车", price:2300000 },
    { name:"宝马 M3 雷霆版",                   brand:"宝马",   category:"性能车", price:900000 },
    { name:"宝马 M5 雷霆版",                   brand:"宝马",   category:"性能车", price:1550000 },
    { name:"宝马 M2 雷霆版",                   brand:"宝马",   category:"性能车", price:620000 },
    { name:"宝马 Z4 M40i",                     brand:"宝马",   category:"性能车", price:668000 },
    { name:"奥迪 RS4 Avant",                   brand:"奥迪",   category:"性能车", price:880000 },
    { name:"奥迪 RS6 Avant performance",       brand:"奥迪",   category:"性能车", price:1450000 },
    { name:"奥迪 RS Q8",                       brand:"奥迪",   category:"性能车", price:1460000 },
    { name:"大众 辉腾 6.0 W12 尊崇版",         brand:"大众",   category:"轿车", price:1300000 },
    { name:"大众 途锐 3.0T 锐尊曜黑版",        brand:"大众",   category:"SUV", price:800000 },
    { name:"阿尔法·罗密欧 Giulia 四叶草",     brand:"阿尔法·罗密欧",category:"性能车", price:1100000 },
    { name:"阿尔法·罗密欧 Stelvio 四叶草",     brand:"阿尔法·罗密欧",category:"性能车", price:1200000 },
    { name:"玛莎拉蒂 Ghibli Trofeo",           brand:"玛莎拉蒂",category:"轿车", price:1580000 },
    { name:"玛莎拉蒂 Quattroporte 总裁",       brand:"玛莎拉蒂",category:"轿车", price:1580000 },
    { name:"捷豹 XFL 3.0T 四驱旗舰版",         brand:"捷豹",   category:"轿车", price:590000 },
    { name:"捷豹 F-PACE SVR",                  brand:"捷豹",   category:"SUV", price:1400000 },
    { name:"捷豹 I-PACE EV400 HSE",            brand:"捷豹",   category:"新能源", price:680000 },
    { name:"凯迪拉克 CT6 40T 铂金版",          brand:"凯迪拉克",category:"轿车", price:810000 },
    { name:"凯迪拉克 XT6 六座铂金运动版",      brand:"凯迪拉克",category:"SUV", price:540000 },
    { name:"林肯 大陆 3.0T 总统版",            brand:"林肯",   category:"轿车", price:520000 },
    { name:"林肯 航海家 2.7T 总统版",          brand:"林肯",   category:"SUV", price:530000 },
    { name:"英菲尼迪 QX80 旗舰版",             brand:"英菲尼迪",category:"SUV", price:1150000 },
    { name:"英菲尼迪 Q60 3.0T 豪华运动版",     brand:"英菲尼迪",category:"跑车", price:620000 },
    { name:"讴歌 NSX 3.5T",                    brand:"讴歌",   category:"跑车", price:3000000 },
    { name:"雷克萨斯 LC500h 运动版",           brand:"雷克萨斯",category:"跑车", price:1300000 },
    { name:"雷克萨斯 RX500h 四驱高配",         brand:"雷克萨斯",category:"SUV", price:680000 },
    { name:"沃尔沃 XC90 T8 插混 智雅版",       brand:"沃尔沃", category:"新能源", price:950000 },
    { name:"沃尔沃 S60 Polestar Engineered",   brand:"沃尔沃", category:"性能车", price:490000 },
    { name:"福特 猛禽 F-150 Raptor",           brand:"福特",   category:"皮卡", price:720000 },
    { name:"福特 F-150 Raptor R",              brand:"福特",   category:"皮卡", price:1500000 },
    { name:"道奇 挑战者 SRT Hellcat",          brand:"道奇",   category:"性能车", price:1200000 },
    { name:"雪佛兰 科尔维特 C8 Stingray",      brand:"雪佛兰", category:"跑车", price:1500000 },
    { name:"克莱斯勒 300C 5.7L 旗舰版",        brand:"克莱斯勒",category:"轿车", price:560000 },
    { name:"摩根 3-Wheeler 限量版",            brand:"摩根",   category:"跑车", price:1200000 },
    { name:"巴博斯 G900 火箭版",               brand:"巴博斯", category:"SUV", price:5000000 },
    { name:"迈巴赫 GLS 600 4MATIC",            brand:"迈巴赫", category:"SUV", price:3200000 },
    { name:"迈巴赫 EQS 680 SUV",               brand:"迈巴赫", category:"新能源", price:2380000 },
    { name:"宾利 欧陆 GT V8",                  brand:"宾利",   category:"跑车", price:3180000 },
    { name:"宾利 欧陆 GT Speed",               brand:"宾利",   category:"跑车", price:4250000 },
    { name:"劳斯莱斯 曜影",                    brand:"劳斯莱斯",category:"跑车", price:4800000 },
    { name:"劳斯莱斯 库里南 Black Badge",      brand:"劳斯莱斯",category:"SUV", price:6800000 },
    { name:"保时捷 911 Dakar",                 brand:"保时捷", category:"跑车", price:2300000 },
    { name:"保时捷 Cayenne S 2.9T",            brand:"保时捷", category:"SUV", price:1380000 },
    { name:"保时捷 Panamera 4S E-Hybrid",      brand:"保时捷", category:"新能源", price:1480000 },
    { name:"法拉利 Purosangue",                brand:"法拉利", category:"SUV", price:4980000 },
    { name:"兰博基尼 Urus Performante",        brand:"兰博基尼",category:"SUV", price:3980000 },
    { name:"迈凯伦 750S Spider",               brand:"迈凯伦", category:"跑车", price:3400000 },
    { name:"阿斯顿马丁 DBX 707",               brand:"阿斯顿马丁",category:"SUV", price:3800000 },
  ],
  /* ==================== 房产（150+ 套，上海真实板块/楼盘） ==================== */
  house: [
    /* —— 松江/郊区刚需及改善 —— */
    { name:"松江大学城·文翔路 老式公房 45㎡",     brand:"松江",   category:"住宅", price:1800000 },
    { name:"松江大学城·三湘四季花城 89㎡",        brand:"松江",   category:"住宅", price:3900000 },
    { name:"松江新城·泰晤士小镇 89㎡",            brand:"松江",   category:"住宅", price:4500000 },
    { name:"松江新城·松江万达广场旁 100㎡",       brand:"松江",   category:"住宅", price:4800000 },
    { name:"松江九亭·奥林匹克花园 110㎡",          brand:"松江",   category:"住宅", price:5200000 },
    { name:"松江泗泾·金地自在城 120㎡",            brand:"松江",   category:"住宅", price:5500000 },
    { name:"松江佘山·佘山一品别墅 320㎡",          brand:"松江",   category:"别墅", price:68000000 },
    { name:"松江佘山·佘山庄园独栋 580㎡",          brand:"松江",   category:"别墅", price:80000000 },
    { name:"松江佘山·世茂佘山庄园 750㎡",          brand:"松江",   category:"别墅", price:120000000 },
    { name:"闵行莘庄·莘城苑 78㎡",                 brand:"闵行",   category:"住宅", price:4100000 },
    { name:"闵行莘庄·万科假日风景 100㎡",          brand:"闵行",   category:"住宅", price:7000000 },
    { name:"闵行七宝·万科城市花园 105㎡",          brand:"闵行",   category:"住宅", price:7200000 },
    { name:"闵行古美·万源城 110㎡",                brand:"闵行",   category:"住宅", price:9500000 },
    { name:"闵行华漕·金臣别墅 400㎡",              brand:"闵行",   category:"别墅", price:85000000 },
    { name:"嘉定南翔·华润中央公园 120㎡",          brand:"嘉定",   category:"住宅", price:5800000 },
    { name:"嘉定新城·保利家园 130㎡",              brand:"嘉定",   category:"住宅", price:5600000 },
    { name:"青浦赵巷·金地天境 150㎡",              brand:"青浦",   category:"住宅", price:7500000 },
    { name:"青浦朱家角·御澜山 联排 180㎡",         brand:"青浦",   category:"别墅", price:11000000 },
    { name:"青浦徐泾·上海蟠龙天地 140㎡",          brand:"青浦",   category:"住宅", price:12000000 },
    { name:"奉贤南桥·绿地香颂 110㎡",              brand:"奉贤",   category:"住宅", price:2800000 },
    { name:"宝山顾村·共富新村 85㎡",               brand:"宝山",   category:"住宅", price:3600000 },
    { name:"宝山杨行·绿地海域天墅 130㎡",          brand:"宝山",   category:"住宅", price:5200000 },
    { name:"金山新城·金山万达广场旁 100㎡",        brand:"金山",   category:"住宅", price:2100000 },
    { name:"崇明·崇明岛别墅 260㎡",                brand:"崇明",   category:"别墅", price:18000000 },

    /* —— 外环/中外环改善 —— */
    { name:"浦东川沙·绿地东上海 95㎡",             brand:"浦东",   category:"住宅", price:6500000 },
    { name:"浦东金桥·金桥瑞仕花园 105㎡",          brand:"浦东",   category:"住宅", price:7800000 },
    { name:"浦东张江·汤臣豪园 110㎡",              brand:"浦东",   category:"住宅", price:11500000 },
    { name:"浦东花木·绿城玉兰花园 130㎡",          brand:"浦东",   category:"住宅", price:13500000 },
    { name:"浦东北蔡·大华锦绣华城 120㎡",          brand:"浦东",   category:"住宅", price:11000000 },
    { name:"浦东塘桥·浦发新里城 100㎡",            brand:"浦东",   category:"住宅", price:9200000 },
    { name:"浦东三林·金地湾流域 110㎡",            brand:"浦东",   category:"住宅", price:8800000 },
    { name:"杨浦五角场·创智天地 90㎡",             brand:"杨浦",   category:"住宅", price:10500000 },
    { name:"杨浦新江湾城·合生高尔夫公寓 140㎡",    brand:"杨浦",   category:"住宅", price:16000000 },
    { name:"虹口凉城·凉城新村 80㎡",               brand:"虹口",   category:"住宅", price:5200000 },
    { name:"普陀真如·高尚领域 110㎡",              brand:"普陀",   category:"住宅", price:9500000 },
    { name:"普陀长风·中海紫御豪庭 150㎡",          brand:"普陀",   category:"住宅", price:16500000 },
    { name:"闸北（静安）·大宁金茂府 120㎡",        brand:"静安",   category:"住宅", price:16000000 },
    { name:"静安大宁·静安府 130㎡",                brand:"静安",   category:"住宅", price:17000000 },
    { name:"静安彭浦·彭浦新村 60㎡",               brand:"静安",   category:"住宅", price:3800000 },

    /* —— 中环/内环 —— */
    { name:"浦东联洋·仁恒河滨城 135㎡",            brand:"浦东",   category:"住宅", price:17000000 },
    { name:"浦东碧云·碧云国际社区 150㎡",          brand:"浦东",   category:"住宅", price:21000000 },
    { name:"浦东源深·上海滩花园洋房 120㎡",        brand:"浦东",   category:"住宅", price:15500000 },
    { name:"浦东陆家嘴·滨江凯旋门 180㎡",          brand:"浦东",   category:"住宅", price:48000000 },
    { name:"浦东陆家嘴·中粮海景壹号 200㎡",        brand:"浦东",   category:"住宅", price:55000000 },
    { name:"浦东陆家嘴·汤臣一品 300㎡",            brand:"浦东",   category:"住宅", price:120000000 },
    { name:"浦东陆家嘴·世茂滨江花园 220㎡",        brand:"浦东",   category:"住宅", price:28000000 },
    { name:"徐汇徐家汇·东方曼哈顿 120㎡",          brand:"徐汇",   category:"住宅", price:16000000 },
    { name:"徐汇徐家汇·尚海湾豪庭 140㎡",          brand:"徐汇",   category:"住宅", price:20000000 },
    { name:"徐汇滨江·尚海湾豪庭 160㎡",            brand:"徐汇",   category:"住宅", price:28000000 },
    { name:"徐汇滨江·云锦东方 180㎡",              brand:"徐汇",   category:"住宅", price:40000000 },
    { name:"徐汇衡山路·永嘉路洋房 100㎡",          brand:"徐汇",   category:"住宅", price:25000000 },
    { name:"黄浦新天地·翠湖天地嘉苑 130㎡",        brand:"黄浦",   category:"住宅", price:30000000 },
    { name:"黄浦新天地·翠湖天地四期 180㎡",        brand:"黄浦",   category:"住宅", price:45000000 },
    { name:"黄浦外滩·外滩九里 150㎡",              brand:"黄浦",   category:"住宅", price:38000000 },
    { name:"黄浦人民广场·上海壹号院 120㎡",        brand:"黄浦",   category:"住宅", price:22000000 },
    { name:"静安南京西路·静安嘉里中心公寓 130㎡",  brand:"静安",   category:"住宅", price:32000000 },
    { name:"静安南京西路·恒隆府 160㎡",            brand:"静安",   category:"住宅", price:42000000 },
    { name:"静安苏河湾·宝格丽公寓 120㎡",          brand:"静安",   category:"住宅", price:18000000 },
    { name:"静安苏河湾·华侨城苏河湾 200㎡",        brand:"静安",   category:"住宅", price:32000000 },
    { name:"长宁古北·古北壹号 200㎡",              brand:"长宁",   category:"住宅", price:35000000 },
    { name:"长宁古北·檀宫别墅 500㎡",              brand:"长宁",   category:"别墅", price:150000000 },
    { name:"长宁虹桥·古北瑞仕花园 110㎡",          brand:"长宁",   category:"住宅", price:12000000 },
    { name:"长宁西郊·西郊庄园 400㎡",              brand:"长宁",   category:"别墅", price:90000000 },
    { name:"虹口北外滩·外滩茂悦公寓 130㎡",        brand:"虹口",   category:"住宅", price:15000000 },
    { name:"虹口北外滩·北外滩来福士公寓 140㎡",    brand:"虹口",   category:"住宅", price:18000000 },
    { name:"杨浦东外滩·阳光城檀悦 140㎡",          brand:"杨浦",   category:"住宅", price:16000000 },
    { name:"普陀长寿路·安远路洋房 90㎡",           brand:"普陀",   category:"住宅", price:11000000 },

    /* —— 顶级豪宅/特殊 —— */
    { name:"浦东陆家嘴·滨江凯旋门顶层复式 400㎡",  brand:"浦东",   category:"豪宅", price:120000000 },
    { name:"黄浦新天地·翠湖天地顶层大平层 350㎡",  brand:"黄浦",   category:"豪宅", price:90000000 },
    { name:"徐汇滨江·尚海湾顶层复式 300㎡",        brand:"徐汇",   category:"豪宅", price:80000000 },
    { name:"静安南京西路·嘉天汇 250㎡",            brand:"静安",   category:"豪宅", price:60000000 },
    { name:"长宁古北·御翠豪庭 300㎡",              brand:"长宁",   category:"豪宅", price:80000000 },
    { name:"松江佘山·紫园8号 庄园独栋 1200㎡",     brand:"松江",   category:"豪宅", price:200000000 },
    { name:"闵行旗忠·绿城玫瑰园 800㎡",            brand:"闵行",   category:"豪宅", price:150000000 },
    { name:"浦东东郊·东郊壹号 900㎡",              brand:"浦东",   category:"豪宅", price:180000000 },
    { name:"浦东东郊·华洲君庭 1000㎡",             brand:"浦东",   category:"豪宅", price:250000000 },
    { name:"静安愚园路·愚园路老洋房 200㎡",        brand:"静安",   category:"老洋房", price:60000000 },
    { name:"徐汇武康路·武康路老洋房 180㎡",        brand:"徐汇",   category:"老洋房", price:80000000 },
    { name:"黄浦思南路·思南公馆 老洋房 250㎡",     brand:"黄浦",   category:"老洋房", price:120000000 },
    { name:"徐汇湖南路·湖南路花园洋房 300㎡",      brand:"徐汇",   category:"老洋房", price:150000000 },
    { name:"浦东前滩·前滩中心公寓 150㎡",          brand:"浦东",   category:"住宅", price:20000000 },
    { name:"浦东前滩·晶耀名邸 130㎡",              brand:"浦东",   category:"住宅", price:18000000 },
    { name:"静安大宁·大宁久光公寓 120㎡",          brand:"静安",   category:"住宅", price:12000000 },
    { name:"黄浦豫园·绿地外滩中心 180㎡",          brand:"黄浦",   category:"住宅", price:26000000 },
    { name:"杨浦定海·杨浦滨江壹号 150㎡",          brand:"杨浦",   category:"住宅", price:16000000 },
    { name:"虹口四川北路·中皇广场 100㎡",          brand:"虹口",   category:"住宅", price:9000000 },
    { name:"普陀长风·中海臻如府 160㎡",            brand:"普陀",   category:"住宅", price:18000000 },

    /* —— 第二批：更多板块 —— */
    { name:"浦东唐镇·绿城玉兰花园二期 130㎡",      brand:"浦东",   category:"住宅", price:12000000 },
    { name:"浦东周浦·保利艾庐 120㎡",              brand:"浦东",   category:"住宅", price:7500000 },
    { name:"浦东惠南·绿地乐和城 100㎡",            brand:"浦东",   category:"住宅", price:3200000 },
    { name:"浦东临港·滴水湖馨苑 90㎡",             brand:"浦东",   category:"住宅", price:3000000 },
    { name:"浦东临港·陆家嘴滴水涟岸 120㎡",        brand:"浦东",   category:"住宅", price:4800000 },
    { name:"浦东外高桥·仁恒森兰雅苑 140㎡",        brand:"浦东",   category:"住宅", price:11000000 },
    { name:"浦东世纪公园·浦东星河湾 200㎡",        brand:"浦东",   category:"住宅", price:30000000 },
    { name:"浦东联洋·仁恒河滨花园 140㎡",          brand:"浦东",   category:"住宅", price:18000000 },
    { name:"徐汇田林·田林新村 70㎡",               brand:"徐汇",   category:"住宅", price:5200000 },
    { name:"徐汇龙华·尚海湾豪庭二期 150㎡",        brand:"徐汇",   category:"住宅", price:24000000 },
    { name:"徐汇华泾·华泾绿苑 100㎡",              brand:"徐汇",   category:"住宅", price:6800000 },
    { name:"徐汇康健·漕河景苑 110㎡",              brand:"徐汇",   category:"住宅", price:9500000 },
    { name:"静安曹家渡·静安枫景 100㎡",            brand:"静安",   category:"住宅", price:10500000 },
    { name:"静安曹家渡·达安花园 120㎡",            brand:"静安",   category:"住宅", price:11500000 },
    { name:"静安闸北·万科翡翠雅宾利 140㎡",        brand:"静安",   category:"住宅", price:15000000 },
    { name:"静安闸北·苏河融创 130㎡",              brand:"静安",   category:"住宅", price:13000000 },
    { name:"黄浦打浦桥·海华花园 90㎡",             brand:"黄浦",   category:"住宅", price:12500000 },
    { name:"黄浦五里桥·盛世滨江 120㎡",            brand:"黄浦",   category:"住宅", price:16000000 },
    { name:"黄浦老西门·复兴珑御 150㎡",            brand:"黄浦",   category:"住宅", price:25000000 },
    { name:"长宁中山公园·中山公寓 100㎡",          brand:"长宁",   category:"住宅", price:11000000 },
    { name:"长宁天山·天山华庭 110㎡",              brand:"长宁",   category:"住宅", price:12000000 },
    { name:"长宁新华路·新华路老洋房 160㎡",        brand:"长宁",   category:"老洋房", price:45000000 },
    { name:"虹口鲁迅公园·瑞虹新城 130㎡",          brand:"虹口",   category:"住宅", price:13500000 },
    { name:"虹口曲阳·曲阳新村 75㎡",               brand:"虹口",   category:"住宅", price:4800000 },
    { name:"虹口临平路·招商外滩玺 120㎡",          brand:"虹口",   category:"住宅", price:14500000 },
    { name:"杨浦控江·控江四村 60㎡",               brand:"杨浦",   category:"住宅", price:4200000 },
    { name:"杨浦平凉·阳光城檀悦二期 130㎡",        brand:"杨浦",   category:"住宅", price:14500000 },
    { name:"杨浦鞍山·鞍山新村 70㎡",               brand:"杨浦",   category:"住宅", price:5000000 },
    { name:"普陀真光·真光新村 70㎡",               brand:"普陀",   category:"住宅", price:4000000 },
    { name:"普陀曹杨·曹杨新村 65㎡",               brand:"普陀",   category:"住宅", price:4200000 },
    { name:"普陀桃浦·智创城住宅 110㎡",            brand:"普陀",   category:"住宅", price:8500000 },
    { name:"宝山共康·共康八村 80㎡",               brand:"宝山",   category:"住宅", price:3500000 },
    { name:"宝山大场·经纬城市绿洲 100㎡",          brand:"宝山",   category:"住宅", price:5200000 },
    { name:"宝山上大·上大聚丰园 90㎡",             brand:"宝山",   category:"住宅", price:4200000 },
    { name:"闵行梅陇·梅陇三村 75㎡",               brand:"闵行",   category:"住宅", price:4800000 },
    { name:"闵行春申·春申景城 110㎡",              brand:"闵行",   category:"住宅", price:6500000 },
    { name:"闵行吴泾·万科阳光苑 100㎡",            brand:"闵行",   category:"住宅", price:5800000 },
    { name:"嘉定安亭·上海汽车城人才公寓 90㎡",     brand:"嘉定",   category:"住宅", price:2800000 },
    { name:"嘉定江桥·万达城市公寓 100㎡",          brand:"嘉定",   category:"住宅", price:4500000 },
    { name:"青浦赵巷·万科有山 联排 160㎡",         brand:"青浦",   category:"别墅", price:9500000 },
    { name:"青浦徐泾·仁恒西郊花园 140㎡",          brand:"青浦",   category:"住宅", price:11000000 },
    { name:"青浦淀山湖·观澜府 220㎡",              brand:"青浦",   category:"别墅", price:20000000 },
    { name:"奉贤海湾·海湾旅游区公寓 100㎡",        brand:"奉贤",   category:"住宅", price:2000000 },
    { name:"金山石化·石化一村 80㎡",               brand:"金山",   category:"住宅", price:1600000 },
    { name:"崇明陈家镇·东滩花园 200㎡",            brand:"崇明",   category:"别墅", price:9000000 },
    { name:"崇明城桥·崇明新城公寓 100㎡",          brand:"崇明",   category:"住宅", price:2200000 },
    { name:"浦东曹路·金钻苑 100㎡",                brand:"浦东",   category:"住宅", price:5500000 },
    { name:"浦东航头·航头家园 90㎡",               brand:"浦东",   category:"住宅", price:4200000 },
    { name:"浦东书院·书院镇公寓 80㎡",             brand:"浦东",   category:"住宅", price:2000000 },
    { name:"徐汇斜土路·枫林路老房 65㎡",           brand:"徐汇",   category:"住宅", price:6200000 },
    { name:"静安天目西路·天目西老房 70㎡",         brand:"静安",   category:"住宅", price:5800000 },

    /* —— 国内其他城市 —— */
    { name:"北京朝阳·望京 SOHO 旁 120㎡",          brand:"北京",   category:"住宅", price:12500000 },
    { name:"北京海淀·万柳书院 150㎡",              brand:"北京",   category:"住宅", price:30000000 },
    { name:"北京西城·金融街 120㎡",                brand:"北京",   category:"住宅", price:20000000 },
    { name:"北京东城·王府井 老房 90㎡",            brand:"北京",   category:"住宅", price:15000000 },
    { name:"北京朝阳·棕榈泉国际公寓 200㎡",        brand:"北京",   category:"住宅", price:28000000 },
    { name:"北京海淀·香山清琴 别墅 500㎡",         brand:"北京",   category:"别墅", price:80000000 },
    { name:"北京顺义·中央别墅区 独栋 600㎡",        brand:"北京",   category:"别墅", price:100000000 },
    { name:"北京朝阳·星河湾 300㎡",                brand:"北京",   category:"豪宅", price:60000000 },
    { name:"深圳南山·深圳湾1号 200㎡",             brand:"深圳",   category:"住宅", price:60000000 },
    { name:"深圳南山·华润深圳湾悦府 180㎡",        brand:"深圳",   category:"住宅", price:45000000 },
    { name:"深圳福田·香蜜湖 150㎡",                brand:"深圳",   category:"住宅", price:25000000 },
    { name:"深圳南山·华侨城波托菲诺 别墅 400㎡",   brand:"深圳",   category:"别墅", price:80000000 },
    { name:"深圳福田·中心区 天元 250㎡",           brand:"深圳",   category:"豪宅", price:50000000 },
    { name:"广州天河·珠江新城 汇悦台 220㎡",       brand:"广州",   category:"住宅", price:45000000 },
    { name:"广州天河·凯旋新世界 180㎡",            brand:"广州",   category:"住宅", price:32000000 },
    { name:"广州天河·侨鑫汇悦台 顶层 300㎡",       brand:"广州",   category:"豪宅", price:80000000 },
    { name:"广州番禺·星河湾 别墅 400㎡",           brand:"广州",   category:"别墅", price:40000000 },
    { name:"杭州西湖·绿城深蓝 150㎡",              brand:"杭州",   category:"住宅", price:22000000 },
    { name:"杭州滨江·银杏汇 200㎡",                brand:"杭州",   category:"住宅", price:35000000 },
    { name:"杭州西湖·云栖玫瑰园 别墅 500㎡",       brand:"杭州",   category:"别墅", price:70000000 },
    { name:"杭州钱江新城·江河汇 250㎡",            brand:"杭州",   category:"豪宅", price:50000000 },
    { name:"苏州园区·金鸡湖畔 200㎡",              brand:"苏州",   category:"住宅", price:28000000 },
    { name:"苏州园区·湖滨四季 别墅 400㎡",         brand:"苏州",   category:"别墅", price:50000000 },
    { name:"南京鼓楼·金陵雅颂居 180㎡",            brand:"南京",   category:"住宅", price:18000000 },
    { name:"南京河西·仁恒江湾城 220㎡",            brand:"南京",   category:"住宅", price:25000000 },
    { name:"成都高新·交子金融城 180㎡",            brand:"成都",   category:"住宅", price:12000000 },
    { name:"成都锦江·麓湖 别墅 400㎡",             brand:"成都",   category:"别墅", price:35000000 },
    { name:"武汉江岸·武汉天地 200㎡",              brand:"武汉",   category:"住宅", price:15000000 },
    { name:"武汉武昌·沙湖 绿城 180㎡",             brand:"武汉",   category:"住宅", price:12000000 },
    { name:"重庆江北·融创壹号院 200㎡",            brand:"重庆",   category:"住宅", price:12000000 },
    { name:"重庆两江·金科九曲河 别墅 400㎡",       brand:"重庆",   category:"别墅", price:25000000 },
    { name:"天津和平·五大道 老洋房 200㎡",         brand:"天津",   category:"老洋房", price:30000000 },
    { name:"天津河西·梅江 别墅 300㎡",             brand:"天津",   category:"别墅", price:20000000 },
    { name:"西安曲江·万众国际 180㎡",              brand:"西安",   category:"住宅", price:10000000 },
    { name:"西安高新·保利天悦 150㎡",              brand:"西安",   category:"住宅", price:8000000 },
    { name:"厦门思明·五缘湾 220㎡",                brand:"厦门",   category:"住宅", price:25000000 },
    { name:"厦门思明·鼓浪屿 老别墅 300㎡",         brand:"厦门",   category:"别墅", price:50000000 },
    { name:"三亚海棠湾·亚特兰蒂斯旁 别墅 300㎡",   brand:"三亚",   category:"别墅", price:45000000 },
    { name:"三亚亚龙湾·高端海景房 200㎡",          brand:"三亚",   category:"住宅", price:22000000 },
    { name:"青岛崂山·石老人 海景 200㎡",           brand:"青岛",   category:"住宅", price:18000000 },
    { name:"大连中山·星海湾 200㎡",                brand:"大连",   category:"住宅", price:12000000 },
    { name:"宁波鄞州·东部新城 180㎡",              brand:"宁波",   category:"住宅", price:10000000 },
    { name:"福州鼓楼·鼓楼区 老宅 150㎡",           brand:"福州",   category:"住宅", price:9000000 },
    { name:"长沙岳麓·梅溪湖 180㎡",                brand:"长沙",   category:"住宅", price:8000000 },
    { name:"郑州郑东·如意湖 200㎡",                brand:"郑州",   category:"住宅", price:9000000 },
    { name:"合肥政务·天鹅湖 200㎡",                brand:"合肥",   category:"住宅", price:10000000 },
    { name:"昆明西山·滇池 别墅 400㎡",             brand:"昆明",   category:"别墅", price:20000000 },
    { name:"桂林七星·漓江边 别墅 300㎡",           brand:"桂林",   category:"别墅", price:15000000 },
    { name:"海口美兰·海甸岛 海景 200㎡",           brand:"海口",   category:"住宅", price:12000000 },
    { name:"珠海横琴·华发广场 180㎡",              brand:"珠海",   category:"住宅", price:15000000 },
    { name:"东莞松山湖·华为小镇旁 别墅 300㎡",     brand:"东莞",   category:"别墅", price:25000000 },
    { name:"无锡滨湖·蠡湖湾 200㎡",                brand:"无锡",   category:"住宅", price:12000000 },
    { name:"常州武进·西太湖 别墅 300㎡",           brand:"常州",   category:"别墅", price:15000000 },

    /* —— 国外热门城市 —— */
    { name:"东京 港区 白金台 高层 120㎡",          brand:"东京",   category:"住宅", price:28000000 },
    { name:"东京 涩谷 松涛 独栋 别墅 200㎡",       brand:"东京",   category:"别墅", price:60000000 },
    { name:"东京 千代田 皇居旁 高层 150㎡",        brand:"东京",   category:"住宅", price:45000000 },
    { name:"东京 银座 塔楼公寓 130㎡",             brand:"东京",   category:"住宅", price:35000000 },
    { name:"大阪 北区 梅田 高层 100㎡",            brand:"大阪",   category:"住宅", price:15000000 },
    { name:"大阪 中央区 心斋桥 公寓 90㎡",         brand:"大阪",   category:"住宅", price:12000000 },
    { name:"京都 东山 町屋 传统宅邸 200㎡",        brand:"京都",   category:"别墅", price:25000000 },
    { name:"首尔 江南区 清潭洞 高层 150㎡",        brand:"首尔",   category:"住宅", price:20000000 },
    { name:"首尔 汉南洞 豪宅 180㎡",               brand:"首尔",   category:"住宅", price:35000000 },
    { name:"首尔 龙山区 汉江景 高层 160㎡",        brand:"首尔",   category:"住宅", price:28000000 },
    { name:"新加坡 乌节路 公寓 150㎡",             brand:"新加坡", category:"住宅", price:45000000 },
    { name:"新加坡 圣淘沙湾 豪宅 300㎡",           brand:"新加坡", category:"豪宅", price:100000000 },
    { name:"新加坡 滨海湾 金沙公寓 200㎡",         brand:"新加坡", category:"住宅", price:80000000 },
    { name:"曼谷 素坤逸 高层 公寓 120㎡",          brand:"曼谷",   category:"住宅", price:5000000 },
    { name:"曼谷 湄南河边 豪宅 200㎡",             brand:"曼谷",   category:"住宅", price:10000000 },
    { name:"伦敦 骑士桥 海德公园旁 公寓 150㎡",    brand:"伦敦",   category:"住宅", price:60000000 },
    { name:"伦敦 梅菲尔 公寓 120㎡",               brand:"伦敦",   category:"住宅", price:50000000 },
    { name:"伦敦 切尔西 联排别墅 200㎡",           brand:"伦敦",   category:"别墅", price:80000000 },
    { name:"巴黎 香榭丽舍 奥斯曼公寓 150㎡",       brand:"巴黎",   category:"住宅", price:45000000 },
    { name:"巴黎 十六区 布洛涅林 公寓 180㎡",      brand:"巴黎",   category:"住宅", price:50000000 },
    { name:"巴黎 圣日耳曼 老公寓 120㎡",           brand:"巴黎",   category:"住宅", price:38000000 },
    { name:"纽约 曼哈顿 中央公园南 公寓 180㎡",    brand:"纽约",   category:"住宅", price:80000000 },
    { name:"纽约 曼哈顿 上东区 公寓 200㎡",        brand:"纽约",   category:"住宅", price:70000000 },
    { name:"纽约 曼哈顿 翠贝卡 复式 250㎡",        brand:"纽约",   category:"住宅", price:100000000 },
    { name:"洛杉矶 比弗利山庄 豪宅 500㎡",         brand:"洛杉矶", category:"豪宅", price:150000000 },
    { name:"洛杉矶 好莱坞山 别墅 400㎡",           brand:"洛杉矶", category:"别墅", price:80000000 },
    { name:"洛杉矶 马里布 海景豪宅 400㎡",         brand:"洛杉矶", category:"豪宅", price:120000000 },
    { name:"旧金山 太平洋高地 维多利亚式 250㎡",   brand:"旧金山", category:"住宅", price:90000000 },
    { name:"旧金山 硅谷 帕洛阿尔托 别墅 300㎡",    brand:"旧金山", category:"别墅", price:120000000 },
    { name:"温哥华 西温哥华 海景豪宅 400㎡",       brand:"温哥华", category:"豪宅", price:80000000 },
    { name:"多伦多 玫瑰谷 豪宅 350㎡",             brand:"多伦多", category:"豪宅", price:50000000 },
    { name:"悉尼 达令港 高层 公寓 200㎡",          brand:"悉尼",   category:"住宅", price:45000000 },
    { name:"悉尼 邦迪海滩 别墅 300㎡",             brand:"悉尼",   category:"别墅", price:50000000 },
    { name:"墨尔本 图拉克 豪宅 300㎡",             brand:"墨尔本", category:"豪宅", price:35000000 },
    { name:"迪拜 棕榈岛 别墅 500㎡",               brand:"迪拜",   category:"豪宅", price:80000000 },
    { name:"迪拜 市中心 哈利法塔旁 公寓 200㎡",    brand:"迪拜",   category:"住宅", price:35000000 },
    { name:"迪拜 朱美拉 海滨豪宅 400㎡",           brand:"迪拜",   category:"豪宅", price:60000000 },
    { name:"苏黎世 苏黎世湖 豪宅 300㎡",           brand:"苏黎世", category:"豪宅", price:100000000 },
    { name:"日内瓦 日内瓦湖 豪宅 250㎡",           brand:"日内瓦", category:"豪宅", price:90000000 },
    { name:"摩纳哥 蒙特卡洛 海景公寓 150㎡",       brand:"摩纳哥", category:"住宅", price:100000000 },
    { name:"米兰 布雷拉 公寓 150㎡",               brand:"米兰",   category:"住宅", price:25000000 },
    { name:"罗马 中心区 公寓 120㎡",               brand:"罗马",   category:"住宅", price:20000000 },
    { name:"巴塞罗那 扩展区 高迪风格 公寓 180㎡",  brand:"巴塞罗那",category:"住宅", price:18000000 },
    { name:"马德里 萨拉曼卡 公寓 150㎡",           brand:"马德里", category:"住宅", price:15000000 },
    { name:"里斯本 自由大道 公寓 120㎡",           brand:"里斯本", category:"住宅", price:10000000 },
    { name:"莫斯科 莫斯科河 公寓 150㎡",           brand:"莫斯科", category:"住宅", price:12000000 },
    { name:"迪拜 棕榈岛 皇家别墅 800㎡",           brand:"迪拜",   category:"豪宅", price:250000000 },
    { name:"纽约 曼哈顿 顶层公寓 400㎡",           brand:"纽约",   category:"豪宅", price:200000000 },
    { name:"伦敦 海德公园一号 顶层 300㎡",         brand:"伦敦",   category:"豪宅", price:250000000 },
    { name:"摩纳哥 顶层 海景 200㎡",               brand:"摩纳哥", category:"豪宅", price:180000000 },
    { name:"悉尼 歌剧院旁 海景 顶层 300㎡",        brand:"悉尼",   category:"豪宅", price:100000000 },
    { name:"东京 六本木新城 顶层 250㎡",           brand:"东京",   category:"豪宅", price:90000000 },
    { name:"新加坡 圣淘沙湾 游艇码头豪宅 500㎡",   brand:"新加坡", category:"豪宅", price:180000000 },
    { name:"夏威夷 檀香山 海滨别墅 400㎡",         brand:"夏威夷", category:"豪宅", price:120000000 },
    { name:"巴厘岛 乌鲁瓦图 悬崖别墅 500㎡",       brand:"巴厘岛", category:"别墅", price:25000000 },
    { name:"普吉岛 苏林 海景别墅 400㎡",           brand:"普吉岛", category:"别墅", price:20000000 },
    { name:"济州岛 海岸 别墅 300㎡",               brand:"济州岛", category:"别墅", price:12000000 },
    { name:"北海道 二世古 滑雪度假屋 200㎡",       brand:"北海道", category:"别墅", price:15000000 },
    { name:"瑞士 采尔马特 雪山木屋 300㎡",         brand:"瑞士",   category:"别墅", price:40000000 },
    { name:"法国 蔚蓝海岸 圣特罗佩 海滨别墅 400㎡",brand:"法国",   category:"豪宅", price:100000000 },
    { name:"意大利 科莫湖 湖畔别墅 500㎡",         brand:"意大利", category:"豪宅", price:120000000 },
    { name:"西班牙 伊比萨 海滨别墅 400㎡",         brand:"西班牙", category:"别墅", price:40000000 },
    { name:"土耳其 伊斯坦布尔 博斯普鲁斯海峡 豪宅 400㎡",brand:"土耳其",category:"豪宅", price:60000000 },
    { name:"泰国 曼谷 湄南河 顶级豪宅 250㎡",      brand:"泰国",   category:"豪宅", price:18000000 },
    { name:"吉隆坡 双子塔旁 公寓 150㎡",           brand:"吉隆坡", category:"住宅", price:8000000 },
    { name:"雅加达 中心区 公寓 150㎡",             brand:"雅加达", category:"住宅", price:6000000 },
    { name:"孟买 马拉巴尔山 豪宅 400㎡",           brand:"孟买",   category:"豪宅", price:50000000 },
    { name:"台北 信义区 101 旁 公寓 150㎡",        brand:"台北",   category:"住宅", price:18000000 },
    { name:"香港 中环 半山 公寓 150㎡",            brand:"香港",   category:"住宅", price:40000000 },
    { name:"香港 浅水湾 海景豪宅 300㎡",           brand:"香港",   category:"豪宅", price:120000000 },
    { name:"香港 太平山 豪宅 400㎡",               brand:"香港",   category:"豪宅", price:180000000 },
    { name:"澳门 路氹 豪宅 250㎡",                 brand:"澳门",   category:"住宅", price:25000000 },
    { name:"澳门 南湾 海景公寓 180㎡",             brand:"澳门",   category:"住宅", price:18000000 },
  ],
  /* ==================== 奢侈品（400 件：名表/包/珠宝/画作/收藏品等） ==================== */
  luxury: [
    /* —— 名表（瑞士制表，公价行情） —— */
    { name:"浪琴 先行者系列 41mm",               brand:"浪琴",     category:"名表", price:18000 },
    { name:"浪琴 名匠系列 40mm",                 brand:"浪琴",     category:"名表", price:23000 },
    { name:"浪琴 康卡斯潜水 43mm",               brand:"浪琴",     category:"名表", price:13500 },
    { name:"欧米茄 海马系列 300米潜水 42mm",     brand:"欧米茄",   category:"名表", price:52000 },
    { name:"欧米茄 海马系列 300米潜水 黑金",     brand:"欧米茄",   category:"名表", price:88000 },
    { name:"欧米茄 超霸系列 月球表 42mm",        brand:"欧米茄",   category:"名表", price:63000 },
    { name:"欧米茄 星座系列 41mm",               brand:"欧米茄",   category:"名表", price:58000 },
    { name:"欧米茄 碟飞系列 典雅 40mm",          brand:"欧米茄",   category:"名表", price:42000 },
    { name:"欧米茄 星座系列 曼哈顿 28mm（女款）",brand:"欧米茄",   category:"名表", price:68000 },
    { name:"劳力士 蚝式恒动 41mm",               brand:"劳力士",   category:"名表", price:56000 },
    { name:"劳力士 潜航者 126610LN（黑水鬼）",   brand:"劳力士",   category:"名表", price:120000 },
    { name:"劳力士 潜航者 126610LV（绿水鬼）",   brand:"劳力士",   category:"名表", price:130000 },
    { name:"劳力士 格林尼治 II 126710BLRO（百事圈）",brand:"劳力士",category:"名表", price:150000 },
    { name:"劳力士 迪通拿 116500LN（熊猫迪）",   brand:"劳力士",   category:"名表", price:350000 },
    { name:"劳力士 日志型 126334 蓝盘",          brand:"劳力士",   category:"名表", price:85000 },
    { name:"劳力士 星期日历型 228238（金劳DD）", brand:"劳力士",   category:"名表", price:380000 },
    { name:"劳力士 探险家 II 226570",            brand:"劳力士",   category:"名表", price:100000 },
    { name:"劳力士 空中霸王型 126900",           brand:"劳力士",   category:"名表", price:68000 },
    { name:"劳力士 游艇名仕型 126622 蓝面",      brand:"劳力士",   category:"名表", price:120000 },
    { name:"劳力士 宇宙计型迪通拿 116518LN 金迪",brand:"劳力士",   category:"名表", price:300000 },
    { name:"百达翡丽 鹦鹉螺 5711/1A-014",        brand:"百达翡丽", category:"名表", price:1800000 },
    { name:"百达翡丽 鹦鹉螺 5712/1A-001",        brand:"百达翡丽", category:"名表", price:2200000 },
    { name:"百达翡丽 年历 5726/1A-001",          brand:"百达翡丽", category:"名表", price:2500000 },
    { name:"百达翡丽 超级复杂功能 5270G",        brand:"百达翡丽", category:"名表", price:2800000 },
    { name:"百达翡丽 星空 6102P",                brand:"百达翡丽", category:"名表", price:5000000 },
    { name:"百达翡丽 卡拉卓华 5227G",            brand:"百达翡丽", category:"名表", price:350000 },
    { name:"百达翡丽 复杂功能 5396G",            brand:"百达翡丽", category:"名表", price:800000 },
    { name:"百达翡丽 女式 7130G 两地时",         brand:"百达翡丽", category:"名表", price:600000 },
    { name:"江诗丹顿 纵横四海 4500V/110A",       brand:"江诗丹顿", category:"名表", price:450000 },
    { name:"江诗丹顿 纵横四海 5500V 计时",       brand:"江诗丹顿", category:"名表", price:550000 },
    { name:"江诗丹顿 传承 85180 白金",           brand:"江诗丹顿", category:"名表", price:380000 },
    { name:"江诗丹顿 传承 4200H 铂金",           brand:"江诗丹顿", category:"名表", price:800000 },
    { name:"江诗丹顿 马耳他系列 陀飞轮",         brand:"江诗丹顿", category:"名表", price:2500000 },
    { name:"江诗丹顿 艺术大师系列 万年历",       brand:"江诗丹顿", category:"名表", price:2000000 },
    { name:"爱彼 皇家橡树 15500ST 蓝面",         brand:"爱彼",     category:"名表", price:450000 },
    { name:"爱彼 皇家橡树 26574 万年历",         brand:"爱彼",     category:"名表", price:1200000 },
    { name:"爱彼 皇家橡树离岸 26420 计时",       brand:"爱彼",     category:"名表", price:600000 },
    { name:"爱彼 皇家橡树 26331 计时",           brand:"爱彼",     category:"名表", price:650000 },
    { name:"爱彼 CODE 11.59 15210",              brand:"爱彼",     category:"名表", price:250000 },
    { name:"积家 大师系列 全历 130842J",         brand:"积家",     category:"名表", price:120000 },
    { name:"积家 翻转系列 计时 Q3872510",        brand:"积家",     category:"名表", price:150000 },
    { name:"积家 双翼系列 陀飞轮",               brand:"积家",     category:"名表", price:800000 },
    { name:"积家 约会系列 女款 Q3448420",        brand:"积家",     category:"名表", price:200000 },
    { name:"宝珀 五十噚 5015 蓝钛",              brand:"宝珀",     category:"名表", price:150000 },
    { name:"宝珀 五十噚 深潜器 5054",            brand:"宝珀",     category:"名表", price:120000 },
    { name:"宝珀 经典系列 6654 全历月相",        brand:"宝珀",     category:"名表", price:150000 },
    { name:"宝珀 Villeret 系列 6639",            brand:"宝珀",     category:"名表", price:280000 },
    { name:"宝玑 经典系列 5177 珐琅盘",          brand:"宝玑",     category:"名表", price:200000 },
    { name:"宝玑 那普勒斯王后 8918 女款",        brand:"宝玑",     category:"名表", price:350000 },
    { name:"宝玑 航海系列 5517",                 brand:"宝玑",     category:"名表", price:250000 },
    { name:"格拉苏蒂原创 议员系列 全历月相",     brand:"格拉苏蒂原创",category:"名表", price:180000 },
    { name:"格拉苏蒂原创 偏心系列 90-02",        brand:"格拉苏蒂原创",category:"名表", price:150000 },
    { name:"格拉苏蒂原创 海洋系列 计时",         brand:"格拉苏蒂原创",category:"名表", price:200000 },
    { name:"万国 IWC 葡萄牙系列 七日链",         brand:"万国",     category:"名表", price:150000 },
    { name:"万国 IWC 飞行员 大飞万年历",         brand:"万国",     category:"名表", price:350000 },
    { name:"万国 IWC 工程师系列 40mm",           brand:"万国",     category:"名表", price:100000 },
    { name:"万国 IWC 达文西系列 计时",           brand:"万国",     category:"名表", price:120000 },
    { name:"卡地亚 蓝气球 42mm",                 brand:"卡地亚",   category:"名表", price:60000 },
    { name:"卡地亚 坦克系列 法坦",               brand:"卡地亚",   category:"名表", price:40000 },
    { name:"卡地亚 山度士 40mm",                 brand:"卡地亚",   category:"名表", price:70000 },
    { name:"卡地亚 帕莎系列 腕表",               brand:"卡地亚",   category:"名表", price:55000 },
    { name:"卡地亚 猎豹系列 女款",               brand:"卡地亚",   category:"名表", price:120000 },
    { name:"沛纳海 Luminor 庐米诺 44mm",         brand:"沛纳海",   category:"名表", price:90000 },
    { name:"沛纳海 Luminor 1950 47mm",           brand:"沛纳海",   category:"名表", price:120000 },
    { name:"沛纳海 Submersible 潜行 47mm",       brand:"沛纳海",   category:"名表", price:150000 },
    { name:"真力时 飞行员系列 青铜 45mm",        brand:"真力时",   category:"名表", price:100000 },
    { name:"真力时 Defy 系列 天际线",            brand:"真力时",   category:"名表", price:90000 },
    { name:"真力时 El Primero 系列 计时",        brand:"真力时",   category:"名表", price:80000 },
    { name:"百年灵 航空计时 41mm",               brand:"百年灵",   category:"名表", price:70000 },
    { name:"百年灵 超级海洋 42mm",               brand:"百年灵",   category:"名表", price:50000 },
    { name:"百年灵 复仇者 45mm",                 brand:"百年灵",   category:"名表", price:60000 },
    { name:"泰格豪雅 卡莱拉系列 计时",           brand:"泰格豪雅", category:"名表", price:50000 },
    { name:"泰格豪雅 竞潜系列 300 43mm",         brand:"泰格豪雅", category:"名表", price:30000 },
    { name:"泰格豪雅 Monaco 摩纳哥系列",         brand:"泰格豪雅", category:"名表", price:80000 },
    { name:"萧邦 快乐钻石系列 女款",             brand:"萧邦",     category:"名表", price:150000 },
    { name:"萧邦 Alpine Eagle 雪山傲翼 41mm",    brand:"萧邦",     category:"名表", price:180000 },
    { name:"罗杰杜彼 王者系列 双陀飞轮",         brand:"罗杰杜彼", category:"名表", price:2500000 },
    { name:"罗杰杜彼 王者系列 单陀飞轮",         brand:"罗杰杜彼", category:"名表", price:1500000 },
    { name:"里查德米尔 RM 11-03 飞返计时",       brand:"里查德米尔",category:"名表", price:3000000 },
    { name:"里查德米尔 RM 055 碳纤维",           brand:"里查德米尔",category:"名表", price:2500000 },
    { name:"里查德米尔 RM 27-04 陀飞轮",         brand:"里查德米尔",category:"名表", price:8000000 },
    { name:"宇舶 Big Bang 融合 42mm",            brand:"宇舶",     category:"名表", price:150000 },
    { name:"宇舶 Big Bang 灵魂 45mm",            brand:"宇舶",     category:"名表", price:250000 },
    { name:"宇舶 经典融合 大教堂三问",           brand:"宇舶",     category:"名表", price:5000000 },
    { name:"帝舵 碧湾 1958 39mm",                brand:"帝舵",     category:"名表", price:28000 },
    { name:"帝舵 皇家系列 41mm",                 brand:"帝舵",     category:"名表", price:22000 },
    { name:"帝舵 领潜型 43mm",                   brand:"帝舵",     category:"名表", price:40000 },
    { name:"豪利时 Aquis 潜水 43.5mm",           brand:"豪利时",   category:"名表", price:25000 },
    { name:"豪利时 大表冠 航空 41mm",            brand:"豪利时",   category:"名表", price:20000 },
    { name:"汉米尔顿 卡其野战 42mm",             brand:"汉米尔顿", category:"名表", price:8000 },
    { name:"汉米尔顿 爵士系列 开心 40mm",        brand:"汉米尔顿", category:"名表", price:12000 },
    { name:"天梭 力洛克系列 39.3mm",             brand:"天梭",     category:"名表", price:6000 },
    { name:"天梭 杜鲁尔系列 80小时 41mm",        brand:"天梭",     category:"名表", price:7000 },
    { name:"雪铁纳 潜水系列 DS 42mm",            brand:"雪铁纳",   category:"名表", price:8000 },
    { name:"美度 舵手系列 42mm",                 brand:"美度",     category:"名表", price:9000 },
    { name:"美度 领航者系列 44mm",               brand:"美度",     category:"名表", price:11000 },
    { name:"精工 冠蓝狮 Grand Seiko 雪花盘",     brand:"精工",     category:"名表", price:45000 },
    { name:"精工 冠蓝狮 44GS 2020 限量",         brand:"精工",     category:"名表", price:50000 },
    { name:"精工 Prospex 潜水 200m",             brand:"精工",     category:"名表", price:15000 },
    { name:"西铁城 光动能 卫星对时 F900",        brand:"西铁城",   category:"名表", price:25000 },
    { name:"卡西欧 海神 OCW-G2000",              brand:"卡西欧",   category:"名表", price:20000 },
    { name:"卡西欧 G-SHOCK MRG-B5000",           brand:"卡西欧",   category:"名表", price:30000 },
    { name:"伯爵 Altiplano 至臻超薄",            brand:"伯爵",     category:"名表", price:150000 },
    { name:"伯爵 Polo 系列 42mm",                brand:"伯爵",     category:"名表", price:200000 },
    { name:"伯爵 玫瑰金链带 女款",               brand:"伯爵",     category:"名表", price:250000 },
    { name:"芝柏 三金桥陀飞轮",                  brand:"芝柏",     category:"名表", price:2500000 },
    { name:"芝柏 恒动力系列 44mm",               brand:"芝柏",     category:"名表", price:180000 },
    { name:"雅典 潜水系列 44mm 蓝钛",            brand:"雅典",     category:"名表", price:150000 },
    { name:"雅典 奇想系列 陀飞轮",               brand:"雅典",     category:"名表", price:500000 },
    { name:"法穆兰 疯狂时刻 Cintrée 45",         brand:"法穆兰",   category:"名表", price:250000 },
    { name:"法穆兰 V45 镂空 45mm",               brand:"法穆兰",   category:"名表", price:350000 },
    { name:"帕玛强尼 通达系列 42mm",             brand:"帕玛强尼", category:"名表", price:200000 },
    { name:"帕玛强尼 通达 陀飞轮 40mm",          brand:"帕玛强尼", category:"名表", price:1500000 },
    { name:"朗格 1815 系列 39mm",                brand:"朗格",     category:"名表", price:350000 },
    { name:"朗格 萨克森系列 40mm",               brand:"朗格",     category:"名表", price:280000 },
    { name:"朗格 大日历系列 41mm",               brand:"朗格",     category:"名表", price:500000 },
    { name:"朗格 陀飞轮 Pour le Mérite",         brand:"朗格",     category:"名表", price:6000000 },
    { name:"格拉汉姆 计时系列 46mm",             brand:"格拉汉姆", category:"名表", price:150000 },
    { name:"豪雅 摩纳哥 湾流限量款",             brand:"泰格豪雅", category:"名表", price:120000 },
    { name:"百年灵 越洋系列 世界时",             brand:"百年灵",   category:"名表", price:120000 },

    /* —— 名牌包（Hermès/Chanel/LV/Gucci 等公价/行情） —— */
    { name:"爱马仕 Birkin 25 金色 Epsom 皮",     brand:"爱马仕",   category:"包包", price:180000 },
    { name:"爱马仕 Birkin 30 黑色 Togo 皮",      brand:"爱马仕",   category:"包包", price:200000 },
    { name:"爱马仕 Birkin 35 棕色 鳄鱼皮",       brand:"爱马仕",   category:"包包", price:650000 },
    { name:"爱马仕 Kelly 25 金扣",               brand:"爱马仕",   category:"包包", price:160000 },
    { name:"爱马仕 Kelly 28 黑金",               brand:"爱马仕",   category:"包包", price:180000 },
    { name:"爱马仕 Constance 24 黑金",           brand:"爱马仕",   category:"包包", price:120000 },
    { name:"爱马仕 Constance 19 大象灰",         brand:"爱马仕",   category:"包包", price:100000 },
    { name:"爱马仕 Picotin 18 菜篮子",           brand:"爱马仕",   category:"包包", price:45000 },
    { name:"爱马仕 Lindy 26 棕色",               brand:"爱马仕",   category:"包包", price:80000 },
    { name:"爱马仕 Roulis 23 大象灰",            brand:"爱马仕",   category:"包包", price:110000 },
    { name:"爱马仕 Mini Kelly 二代 亮面鳄鱼",    brand:"爱马仕",   category:"包包", price:450000 },
    { name:"香奈儿 CF 中号 黑色羊皮金链",        brand:"香奈儿",   category:"包包", price:75000 },
    { name:"香奈儿 CF 大号 黑色荔枝牛皮",        brand:"香奈儿",   category:"包包", price:82000 },
    { name:"香奈儿 2.55 中号 做旧金链",          brand:"香奈儿",   category:"包包", price:70000 },
    { name:"香奈儿 22 包 黑色小羊皮",            brand:"香奈儿",   category:"包包", price:55000 },
    { name:"香奈儿 19 包 中号 米色",             brand:"香奈儿",   category:"包包", price:60000 },
    { name:"香奈儿 流浪包 Gabrielle 中号",       brand:"香奈儿",   category:"包包", price:45000 },
    { name:"香奈儿 WOC 链条钱包 黑色",           brand:"香奈儿",   category:"包包", price:35000 },
    { name:"香奈儿 山茶花限量款 手工钉珠",       brand:"香奈儿",   category:"包包", price:120000 },
    { name:"路易威登 Capucines MM 黑色",         brand:"路易威登", category:"包包", price:60000 },
    { name:"路易威登 Speedy 25 老花",            brand:"路易威登", category:"包包", price:18000 },
    { name:"路易威登 Neverfull MM 老花",         brand:"路易威登", category:"包包", price:16000 },
    { name:"路易威登 Keepall 50 老花",           brand:"路易威登", category:"包包", price:25000 },
    { name:"路易威登 硬箱 Petite Malle",         brand:"路易威登", category:"包包", price:80000 },
    { name:"路易威登 邮差包 老花",               brand:"路易威登", category:"包包", price:20000 },
    { name:"路易威登 三合一 链条包",             brand:"路易威登", category:"包包", price:25000 },
    { name:"迪奥 Lady Dior 中号 藤格纹",         brand:"迪奥",     category:"包包", price:45000 },
    { name:"迪奥 Lady Dior 小号 粉色",           brand:"迪奥",     category:"包包", price:40000 },
    { name:"迪奥 马鞍包 黑色 Oblique",           brand:"迪奥",     category:"包包", price:38000 },
    { name:"迪奥 Book Tote 大号 刺绣",           brand:"迪奥",     category:"包包", price:28000 },
    { name:"迪奥 戴妃包 迷你 珠光粉",            brand:"迪奥",     category:"包包", price:35000 },
    { name:"普拉达 Galleria 中号 黑色 Saffiano", brand:"普拉达",   category:"包包", price:35000 },
    { name:"普拉达 杀手包 Galleria 大号",        brand:"普拉达",   category:"包包", price:40000 },
    { name:"普拉达 Re-Edition 2005 尼龙",        brand:"普拉达",   category:"包包", price:20000 },
    { name:"古驰 Dionysus 酒神 中号 GG",         brand:"古驰",     category:"包包", price:25000 },
    { name:"古驰 Jackie 1961 中号",              brand:"古驰",     category:"包包", price:28000 },
    { name:"古驰 Marmont 中号 绗缝",             brand:"古驰",     category:"包包", price:22000 },
    { name:"古驰 1955 马衔扣 中号",              brand:"古驰",     category:"包包", price:24000 },
    { name:"古驰 竹节包 Bamboo 1947",            brand:"古驰",     category:"包包", price:35000 },
    { name:"葆蝶家 编织包 Cassette 中号",        brand:"葆蝶家",   category:"包包", price:25000 },
    { name:"葆蝶家 云朵包 Andiamo 中号",         brand:"葆蝶家",   category:"包包", price:28000 },
    { name:"葆蝶家 编织肩带 大号",               brand:"葆蝶家",   category:"包包", price:22000 },
    { name:"芬迪 Peekaboo 中号 黑色",            brand:"芬迪",     category:"包包", price:30000 },
    { name:"芬迪 法棍包 Baguette 中号",          brand:"芬迪",     category:"包包", price:28000 },
    { name:"芬迪 老花法棍 迷你",                 brand:"芬迪",     category:"包包", price:22000 },
    { name:"思琳 Triomphe 凯旋门 中号",          brand:"思琳",     category:"包包", price:30000 },
    { name:"思琳 Luggage 笑脸包 中号",           brand:"思琳",     category:"包包", price:28000 },
    { name:"思琳 16 手袋 中号",                  brand:"思琳",     category:"包包", price:32000 },
    { name:"罗意威 Puzzle 拼图包 中号",          brand:"罗意威",   category:"包包", price:28000 },
    { name:"罗意威 Hammock 吊床包 中号",         brand:"罗意威",   category:"包包", price:26000 },
    { name:"罗意威 Flamenco 弗拉门戈 小号",      brand:"罗意威",   category:"包包", price:22000 },
    { name:"宝格丽 Serpenti 蛇头包 小号",        brand:"宝格丽",   category:"包包", price:45000 },
    { name:"宝格丽 Serpenti Forever 手拿包",     brand:"宝格丽",   category:"包包", price:38000 },
    { name:"圣罗兰 Kate 中号 链条包",            brand:"圣罗兰",   category:"包包", price:25000 },
    { name:"圣罗兰 Niki 中号 做旧皮",            brand:"圣罗兰",   category:"包包", price:28000 },
    { name:"圣罗兰 曼哈顿 中号",                 brand:"圣罗兰",   category:"包包", price:32000 },
    { name:"赛琳 Ava 腋下包",                    brand:"赛琳",     category:"包包", price:22000 },
    { name:"德尔沃 Brilliant 中号 黑白",         brand:"德尔沃",   category:"包包", price:65000 },
    { name:"德尔沃 Tempête 中号 黑色",           brand:"德尔沃",   category:"包包", price:60000 },
    { name:"莫罗伯拉尼克 手袋 限量款",           brand:"莫罗伯拉尼克",category:"包包", price:50000 },
    { name:"华伦天奴 Rockstud 铆钉包 中号",      brand:"华伦天奴", category:"包包", price:30000 },
    { name:"华伦天奴 洛克铆钉 链条包",           brand:"华伦天奴", category:"包包", price:28000 },
    { name:"Miu Miu 羊皮包 小号",                brand:"Miu Miu",  category:"包包", price:25000 },
    { name:"Miu Miu 褶皱包 Wander 中号",         brand:"Miu Miu",  category:"包包", price:28000 },
    { name:"巴黎世家 机车包 City 中号",          brand:"巴黎世家", category:"包包", price:22000 },
    { name:"巴黎世家 沙漏包 Le Cagole 中号",     brand:"巴黎世家", category:"包包", price:25000 },
    { name:"托德斯 Di Bag 中号",                 brand:"托德斯",   category:"包包", price:20000 },
    { name:"戈雅 Artois 中号",                   brand:"戈雅",     category:"包包", price:20000 },
    { name:"朗万 经典手袋 中号",                 brand:"朗万",     category:"包包", price:18000 },
    { name:"迈宝瑞 Somerset 中号",               brand:"迈宝瑞",   category:"包包", price:20000 },
    { name:"邦马利 手袋 中号",                   brand:"邦马利",   category:"包包", price:15000 },
    { name:"爱马仕 Birkin 限量 喜马拉雅鳄鱼",    brand:"爱马仕",   category:"包包", price:3500000 },
    { name:"爱马仕 Kelly 喜马拉雅 25",           brand:"爱马仕",   category:"包包", price:2000000 },
    { name:"爱马仕 限量款 雾面鳄鱼 30",          brand:"爱马仕",   category:"包包", price:1200000 },
    { name:"香奈儿 限量 手工坊系列 链条包",      brand:"香奈儿",   category:"包包", price:150000 },
    { name:"路易威登 硬箱 行李箱 定制款",        brand:"路易威登", category:"包包", price:200000 },
    { name:"古驰 迪斯尼联名 限量款",             brand:"古驰",     category:"包包", price:60000 },
    { name:"芬迪 皮草限量 法棍",                 brand:"芬迪",     category:"包包", price:80000 },
    { name:"葆蝶家 编织 限量 稀有皮",            brand:"葆蝶家",   category:"包包", price:100000 },

    /* —— 珠宝/首饰 —— */
    { name:"梵克雅宝 四叶草项链 18K金 红玉髓",   brand:"梵克雅宝", category:"珠宝", price:45000 },
    { name:"梵克雅宝 四叶草手链 18K金 黑玛瑙",   brand:"梵克雅宝", category:"珠宝", price:42000 },
    { name:"梵克雅宝 四叶草耳环 18K金 孔雀石",   brand:"梵克雅宝", category:"珠宝", price:55000 },
    { name:"梵克雅宝 四叶草 戒指 白贝母",        brand:"梵克雅宝", category:"珠宝", price:38000 },
    { name:"梵克雅宝 四叶草 限量 钻石款",        brand:"梵克雅宝", category:"珠宝", price:150000 },
    { name:"卡地亚 Love 系列 手镯 18K玫瑰金",    brand:"卡地亚",   category:"珠宝", price:85000 },
    { name:"卡地亚 Love 系列 戒指 18K白金",      brand:"卡地亚",   category:"珠宝", price:30000 },
    { name:"卡地亚 钉子系列 手镯 18K黄金",       brand:"卡地亚",   category:"珠宝", price:90000 },
    { name:"卡地亚 猎豹系列 项链 钻石",          brand:"卡地亚",   category:"珠宝", price:120000 },
    { name:"卡地亚 三环戒指 18K三色金",          brand:"卡地亚",   category:"珠宝", price:45000 },
    { name:"蒂芙尼 T 系列 手镯 18K玫瑰金",       brand:"蒂芙尼",   category:"珠宝", price:38000 },
    { name:"蒂芙尼 微笑项链 小号 18K黄金",        brand:"蒂芙尼",   category:"珠宝", price:18000 },
    { name:"蒂芙尼 六爪钻戒 1克拉",              brand:"蒂芙尼",   category:"珠宝", price:280000 },
    { name:"蒂芙尼 钥匙吊坠 铂金镶钻",           brand:"蒂芙尼",   category:"珠宝", price:68000 },
    { name:"蒂芙尼 HardWear 手链 18K金",         brand:"蒂芙尼",   category:"珠宝", price:85000 },
    { name:"宝格丽 B.Zero1 系列 项链 18K玫瑰金", brand:"宝格丽",   category:"珠宝", price:45000 },
    { name:"宝格丽 B.Zero1 戒指 18K玫瑰金",      brand:"宝格丽",   category:"珠宝", price:32000 },
    { name:"宝格丽 Serpenti 蛇形手镯 18K金",     brand:"宝格丽",   category:"珠宝", price:150000 },
    { name:"宝格丽 Divas' Dream 项链 钻石",      brand:"宝格丽",   category:"珠宝", price:68000 },
    { name:"宝格丽 祖母绿戒指 1.5克拉",          brand:"宝格丽",   category:"珠宝", price:450000 },
    { name:"宝诗龙 Quatre 系列 戒指 白陶瓷",     brand:"宝诗龙",   category:"珠宝", price:25000 },
    { name:"宝诗龙 Quatre 系列 手镯 金色",       brand:"宝诗龙",   category:"珠宝", price:55000 },
    { name:"戴比尔斯 钻石耳环 1克拉",            brand:"戴比尔斯", category:"珠宝", price:120000 },
    { name:"戴比尔斯 永恒钻戒 0.5克拉",          brand:"戴比尔斯", category:"珠宝", price:80000 },
    { name:"格拉夫 钻石项链 5克拉",              brand:"格拉夫",   category:"珠宝", price:2500000 },
    { name:"格拉夫 钻石戒指 2克拉",              brand:"格拉夫",   category:"珠宝", price:1200000 },
    { name:"宝曼兰朵 波顿 手镯 18K金",           brand:"宝曼兰朵", category:"珠宝", price:40000 },
    { name:"宝曼兰朵 波顿 戒指 18K金",           brand:"宝曼兰朵", category:"珠宝", price:30000 },
    { name:"克罗心 十字架 项链 925银",           brand:"克罗心",   category:"珠宝", price:28000 },
    { name:"克罗心 戒指 925银 十字",             brand:"克罗心",   category:"珠宝", price:18000 },
    { name:"克罗心 手链 925银 十字",             brand:"克罗心",   category:"珠宝", price:22000 },
    { name:"克罗心 耳钉 925银",                  brand:"克罗心",   category:"珠宝", price:15000 },
    { name:"克罗心 皮带扣 18K金 限量",           brand:"克罗心",   category:"珠宝", price:80000 },
    { name:"尚美巴黎 约瑟芬 皇冠戒指 1克拉",     brand:"尚美巴黎", category:"珠宝", price:250000 },
    { name:"尚美巴黎 网蔓 系列 项链",            brand:"尚美巴黎", category:"珠宝", price:85000 },
    { name:"尚美巴黎 白鹭 系列 耳环",            brand:"尚美巴黎", category:"珠宝", price:68000 },
    { name:"弗雷德 Force 10 手链 18K金",         brand:"弗雷德",   category:"珠宝", price:30000 },
    { name:"弗雷德 Force 10 项链 18K金",         brand:"弗雷德",   category:"珠宝", price:28000 },
    { name:"梅西卡 六角星 项链 18K金",           brand:"梅西卡",   category:"珠宝", price:25000 },
    { name:"梅西卡 My Trio 戒指 18K金",          brand:"梅西卡",   category:"珠宝", price:20000 },
    { name:"蒲昔拉蒂 Opera 系列 项链",           brand:"蒲昔拉蒂", category:"珠宝", price:450000 },
    { name:"蒲昔拉蒂 Monete 系列 手链 古币",     brand:"蒲昔拉蒂", category:"珠宝", price:350000 },
    { name:"萧邦 快乐钻石 手镯 18K金",           brand:"萧邦",     category:"珠宝", price:120000 },
    { name:"萧邦 冰蓝钻石 项链 1克拉",           brand:"萧邦",     category:"珠宝", price:850000 },
    { name:"宝格丽 香氛珠宝 女款 项链",          brand:"宝格丽",   category:"珠宝", price:35000 },
    { name:"蒂芙尼 传奇 蓝钻 项链 1克拉",        brand:"蒂芙尼",   category:"珠宝", price:3000000 },

    /* —— 女款首饰（可送女生） —— */
    { name:"卡地亚 猎豹 钻戒 女款 0.5克拉",      brand:"卡地亚",   category:"女款首饰", price:250000 },
    { name:"卡地亚 猎豹 项链 女款 钻石",         brand:"卡地亚",   category:"女款首饰", price:380000 },
    { name:"卡地亚 Love 项链 女款 18K金",        brand:"卡地亚",   category:"女款首饰", price:32000 },
    { name:"卡地亚 Love 耳钉 女款 18K金",        brand:"卡地亚",   category:"女款首饰", price:38000 },
    { name:"梵克雅宝 四叶草 手链 女款 玫瑰金",   brand:"梵克雅宝", category:"女款首饰", price:42000 },
    { name:"梵克雅宝 四叶草 戒指 女款 玫瑰金",   brand:"梵克雅宝", category:"女款首饰", price:35000 },
    { name:"梵克雅宝 四叶草 项链 女款 白K金",    brand:"梵克雅宝", category:"女款首饰", price:48000 },
    { name:"蒂芙尼 六爪钻戒 女款 0.7克拉",       brand:"蒂芙尼",   category:"女款首饰", price:180000 },
    { name:"蒂芙尼 单石钻戒 女款 0.5克拉",       brand:"蒂芙尼",   category:"女款首饰", price:120000 },
    { name:"蒂芙尼 微笑项链 女款 18K金 小号",    brand:"蒂芙尼",   category:"女款首饰", price:15000 },
    { name:"蒂芙尼 蝴蝶结 手链 女款 18K金",      brand:"蒂芙尼",   category:"女款首饰", price:25000 },
    { name:"宝格丽 Serpenti 戒指 女款 18K金",    brand:"宝格丽",   category:"女款首饰", price:45000 },
    { name:"宝格丽 Serpenti 项链 女款 18K金",    brand:"宝格丽",   category:"女款首饰", price:55000 },
    { name:"宝格丽 白贝母 项链 女款 18K金",      brand:"宝格丽",   category:"女款首饰", price:38000 },
    { name:"宝格丽 玫瑰金 手镯 女款 B.Zero1",    brand:"宝格丽",   category:"女款首饰", price:32000 },
    { name:"戴比尔斯 求婚钻戒 女款 1克拉",       brand:"戴比尔斯", category:"女款首饰", price:380000 },
    { name:"戴比尔斯 钻戒 女款 0.5克拉 经典",    brand:"戴比尔斯", category:"女款首饰", price:180000 },
    { name:"戴比尔斯 钻石吊坠 女款 0.3克拉",     brand:"戴比尔斯", category:"女款首饰", price:68000 },
    { name:"尚美巴黎 约瑟芬 钻戒 女款 0.7克拉",  brand:"尚美巴黎", category:"女款首饰", price:280000 },
    { name:"尚美巴黎 蜂巢 项链 女款 18K金",      brand:"尚美巴黎", category:"女款首饰", price:38000 },
    { name:"尚美巴黎 白鹭 耳钉 女款 钻石",       brand:"尚美巴黎", category:"女款首饰", price:85000 },
    { name:"格拉夫 求婚钻戒 女款 2克拉",         brand:"格拉夫",   category:"女款首饰", price:1800000 },
    { name:"格拉夫 钻石耳环 女款 1克拉",         brand:"格拉夫",   category:"女款首饰", price:450000 },
    { name:"格拉夫 钻石手链 女款 2克拉",         brand:"格拉夫",   category:"女款首饰", price:680000 },
    { name:"香奈儿 山茶花 项链 女款 18K金",      brand:"香奈儿",   category:"女款首饰", price:45000 },
    { name:"香奈儿 COCO 钻戒 女款",              brand:"香奈儿",   category:"女款首饰", price:120000 },
    { name:"香奈儿 山茶花 耳环 女款 18K金",      brand:"香奈儿",   category:"女款首饰", price:55000 },
    { name:"迪奥 Rose 玫瑰 项链 女款 18K金",     brand:"迪奥",     category:"女款首饰", price:28000 },
    { name:"迪奥 Rose 玫瑰 戒指 女款 18K金",     brand:"迪奥",     category:"女款首饰", price:25000 },
    { name:"宝诗龙 Quatre 戒指 女款 白陶瓷",     brand:"宝诗龙",   category:"女款首饰", price:25000 },
    { name:"宝诗龙 Quatre 项链 女款 18K金",      brand:"宝诗龙",   category:"女款首饰", price:35000 },
    { name:"弗雷德 Force 10 手链 女款 18K金",    brand:"弗雷德",   category:"女款首饰", price:28000 },
    { name:"弗雷德 爱情锁 项链 女款 18K金",      brand:"弗雷德",   category:"女款首饰", price:25000 },
    { name:"梅西卡 六角星 戒指 女款 18K金",      brand:"梅西卡",   category:"女款首饰", price:22000 },
    { name:"梅西卡 My Trio 项链 女款 18K金",     brand:"梅西卡",   category:"女款首饰", price:20000 },
    { name:"蒲昔拉蒂 Opera 戒指 女款 钻石",      brand:"蒲昔拉蒂", category:"女款首饰", price:380000 },
    { name:"蒲昔拉蒂 莫内特 古币 手链 女款",     brand:"蒲昔拉蒂", category:"女款首饰", price:320000 },
    { name:"萧邦 快乐钻石 戒指 女款 18K金",      brand:"萧邦",     category:"女款首饰", price:68000 },
    { name:"萧邦 Happy Hearts 项链 女款",        brand:"萧邦",     category:"女款首饰", price:45000 },
    { name:"宝曼兰朵 Nudo 戒指 女款 18K金",      brand:"宝曼兰朵", category:"女款首饰", price:28000 },
    { name:"宝曼兰朵 波顿 手镯 女款 18K金",      brand:"宝曼兰朵", category:"女款首饰", price:38000 },
    { name:"格拉夫 蝴蝶 项链 女款 钻石",         brand:"格拉夫",   category:"女款首饰", price:850000 },
    { name:"戴比尔斯 永恒 手链 女款 钻石",       brand:"戴比尔斯", category:"女款首饰", price:280000 },
    { name:"卡地亚 Solitaire 1895 钻戒 女款 1克拉",brand:"卡地亚", category:"女款首饰", price:450000 },
    { name:"卡地亚 1895 系列 钻戒 女款 0.5克拉", brand:"卡地亚",   category:"女款首饰", price:220000 },
    { name:"蒂芙尼 皇冠 钻戒 女款 0.8克拉",      brand:"蒂芙尼",   category:"女款首饰", price:260000 },
    { name:"尚美巴黎 约瑟芬 钻戒 女款 1克拉",    brand:"尚美巴黎", category:"女款首饰", price:520000 },
    { name:"香奈儿 山茶花 钻戒 女款 0.3克拉",    brand:"香奈儿",   category:"女款首饰", price:98000 },
    { name:"梵克雅宝 Perlee 戒指 女款 钻石",     brand:"梵克雅宝", category:"女款首饰", price:68000 },
    { name:"梵克雅宝 Perlee 手镯 女款 18K金",    brand:"梵克雅宝", category:"女款首饰", price:52000 },
    { name:"宝格丽 Divas' Dream 耳环 女款 18K金",brand:"宝格丽",   category:"女款首饰", price:42000 },
    { name:"宝格丽 Diva 吊坠 女款 白贝母",       brand:"宝格丽",   category:"女款首饰", price:32000 },
    { name:"卡地亚 猎豹 手镯 女款 18K金",        brand:"卡地亚",   category:"女款首饰", price:68000 },
    { name:"蒂芙尼 Return to Tiffany 项链 女款", brand:"蒂芙尼",   category:"女款首饰", price:8000 },
    { name:"蒂芙尼 Return to Tiffany 手链 女款", brand:"蒂芙尼",   category:"女款首饰", price:6500 },
    { name:"潘多拉 手链 女款 925银",             brand:"潘多拉",   category:"女款首饰", price:3000 },
    { name:"潘多拉 项链 女款 925银",             brand:"潘多拉",   category:"女款首饰", price:2500 },
    { name:"施华洛世奇 天鹅 项链 女款",          brand:"施华洛世奇",category:"女款首饰", price:2500 },
    { name:"施华洛世奇 天鹅 手链 女款",          brand:"施华洛世奇",category:"女款首饰", price:2000 },
    { name:"APM Monaco 星星 耳环 女款",          brand:"APM",     category:"女款首饰", price:2000 },
    { name:"APM Monaco 星星 项链 女款",          brand:"APM",     category:"女款首饰", price:1800 },
    { name:"周大福 传承 金镯 女款 30g",          brand:"周大福",   category:"女款首饰", price:20000 },
    { name:"周大福 传承 项链 女款 20g",          brand:"周大福",   category:"女款首饰", price:14000 },
    { name:"周生生 钻戒 女款 0.3克拉",           brand:"周生生",   category:"女款首饰", price:28000 },
    { name:"周生生 项链 女款 18K金",             brand:"周生生",   category:"女款首饰", price:8000 },
    { name:"谢瑞麟 钻戒 女款 0.5克拉",           brand:"谢瑞麟",   category:"女款首饰", price:45000 },
    { name:"六福珠宝 黄金 项链 女款",            brand:"六福珠宝", category:"女款首饰", price:12000 },
    { name:"老凤祥 黄金 手镯 女款 25g",          brand:"老凤祥",   category:"女款首饰", price:18000 },
    { name:"I Do 钻戒 女款 0.5克拉",             brand:"I Do",     category:"女款首饰", price:58000 },
    { name:"I Do 对戒 女戒 18K金",               brand:"I Do",     category:"女款首饰", price:28000 },
    { name:"DR 求婚钻戒 女款 0.7克拉",           brand:"DR",       category:"女款首饰", price:88000 },
    { name:"DR 求婚钻戒 女款 1克拉",             brand:"DR",       category:"女款首饰", price:158000 },
    { name:"莱绅通灵 钻戒 女款 0.5克拉",         brand:"莱绅通灵", category:"女款首饰", price:48000 },
    { name:"金伯利 钻戒 女款 1克拉",             brand:"金伯利",   category:"女款首饰", price:128000 },
    { name:"潮宏基 花丝 手镯 女款 18K金",        brand:"潮宏基",   category:"女款首饰", price:15000 },
    { name:"曼卡龙 项链 女款 18K金",             brand:"曼卡龙",   category:"女款首饰", price:6000 },
    { name:"通灵珠宝 蓝火 钻戒 女款 0.3克拉",    brand:"通灵珠宝", category:"女款首饰", price:22000 },
    { name:"老庙黄金 金镯 女款 40g",             brand:"老庙黄金", category:"女款首饰", price:28000 },
    { name:"中国黄金 金项链 女款 30g",           brand:"中国黄金", category:"女款首饰", price:21000 },
    { name:"周大福 传承 戒指 女款 10g",          brand:"周大福",   category:"女款首饰", price:7000 },
    { name:"谢瑞麟 黄金 项链 女款",              brand:"谢瑞麟",   category:"女款首饰", price:9000 },
    { name:"六福珠宝 钻戒 女款 0.3克拉",         brand:"六福珠宝", category:"女款首饰", price:25000 },
    { name:"梵克雅宝 四叶草 胸针 女款 18K金",    brand:"梵克雅宝", category:"女款首饰", price:68000 },
    { name:"卡地亚 猎豹 胸针 女款 钻石",         brand:"卡地亚",   category:"女款首饰", price:150000 },
    { name:"蒂芙尼 蝴蝶 胸针 女款 18K金",        brand:"蒂芙尼",   category:"女款首饰", price:38000 },
    { name:"宝格丽 Serpenti 手表 女款 18K金",    brand:"宝格丽",   category:"女款首饰", price:180000 },
    { name:"卡地亚 蓝气球 手表 女款 33mm",       brand:"卡地亚",   category:"女款首饰", price:120000 },
    { name:"香奈儿 J12 手表 女款 38mm",          brand:"香奈儿",   category:"女款首饰", price:150000 },
    { name:"萧邦 Happy Sport 手表 女款",         brand:"萧邦",     category:"女款首饰", price:180000 },
    { name:"梵克雅宝 手表 女款 诗文系列",        brand:"梵克雅宝", category:"女款首饰", price:250000 },
    { name:"欧米茄 星座 手表 女款 29mm",         brand:"欧米茄",   category:"女款首饰", price:68000 },
    { name:"宝格丽 Divas' Dream 手表 女款",      brand:"宝格丽",   category:"女款首饰", price:120000 },
    { name:"浪琴 心月 手表 女款 29mm",           brand:"浪琴",     category:"女款首饰", price:25000 },
    { name:"天梭 力洛克 手表 女款 29mm",         brand:"天梭",     category:"女款首饰", price:6000 },
    { name:"卡西欧 小方块 手表 女款",            brand:"卡西欧",   category:"女款首饰", price:1200 },
    { name:"劳力士 女装日志 279174 28mm",        brand:"劳力士",   category:"女款首饰", price:68000 },
    { name:"劳力士 女装蚝式恒动 276200 28mm",    brand:"劳力士",   category:"女款首饰", price:62000 },
    { name:"百达翡丽 女装 7118/1A 鹦鹉螺 35mm",  brand:"百代翡丽", category:"女款首饰", price:680000 },
    { name:"爱彼 皇家橡树 女款 77451ST 34mm",    brand:"爱彼",     category:"女款首饰", price:250000 },
    { name:"江诗丹顿 传袭 女款 82035 36mm",      brand:"江诗丹顿", category:"女款首饰", price:280000 },

    /* —— 画作/艺术品/收藏品 —— */
    { name:"草间弥生 南瓜 版画 限量签名",        brand:"草间弥生", category:"画作", price:350000 },
    { name:"草间弥生 无限网 布面油画 小尺寸",    brand:"草间弥生", category:"画作", price:1200000 },
    { name:"村上隆 太阳花 版画 限量",            brand:"村上隆",   category:"画作", price:80000 },
    { name:"村上隆 太阳花 雕塑 限量",            brand:"村上隆",   category:"收藏品", price:180000 },
    { name:"杰夫·昆斯 气球狗 不锈钢 限量",      brand:"杰夫·昆斯",category:"收藏品", price:2500000 },
    { name:"KAWS 同伴 搪胶 限量",                brand:"KAWS",    category:"收藏品", price:120000 },
    { name:"KAWS 木制 同伴 巨大",                brand:"KAWS",    category:"收藏品", price:1500000 },
    { name:"班克斯 气球女孩 版画 限量",          brand:"班克斯",   category:"画作", price:800000 },
    { name:"班克斯 持气球女孩 油画",             brand:"班克斯",   category:"画作", price:12000000 },
    { name:"奈良美智 小女孩 版画 签名",          brand:"奈良美智", category:"画作", price:450000 },
    { name:"奈良美智 大头女孩 布面油画",         brand:"奈良美智", category:"画作", price:8000000 },
    { name:"吴冠中 江南水乡 水墨 小尺寸",        brand:"吴冠中",   category:"画作", price:800000 },
    { name:"吴冠中 狮子林 油画",                 brand:"吴冠中",   category:"画作", price:8000000 },
    { name:"齐白石 虾 立轴 真迹",                brand:"齐白石",   category:"画作", price:3000000 },
    { name:"张大千 泼墨山水 真迹",               brand:"张大千",   category:"画作", price:5000000 },
    { name:"徐悲鸿 奔马 立轴 真迹",              brand:"徐悲鸿",   category:"画作", price:4500000 },
    { name:"傅抱石 山水 真迹",                   brand:"傅抱石",   category:"画作", price:6000000 },
    { name:"赵无极 抽象 油画 小尺寸",            brand:"赵无极",   category:"画作", price:3500000 },
    { name:"赵无极 无题 大尺幅 油画",            brand:"赵无极",   category:"画作", price:25000000 },
    { name:"常玉 裸女 油画 小尺寸",              brand:"常玉",     category:"画作", price:50000000 },
    { name:"毕加索 版画 限量签名",               brand:"毕加索",   category:"画作", price:1500000 },
    { name:"毕加索 静物 油画 小尺寸",            brand:"毕加索",   category:"画作", price:35000000 },
    { name:"莫奈 睡莲 版画 限量",                brand:"莫奈",     category:"画作", price:1200000 },
    { name:"梵高 向日葵 版画 限量",              brand:"梵高",     category:"画作", price:800000 },
    { name:"安迪·沃霍尔 金宝汤罐头 版画 限量",  brand:"安迪·沃霍尔",category:"画作", price:900000 },
    { name:"安迪·沃霍尔 玛丽莲梦露 丝网版画",   brand:"安迪·沃霍尔",category:"画作", price:2500000 },
    { name:"达米安·赫斯特 药丸柜 装置 限量",    brand:"达米安·赫斯特",category:"收藏品", price:1800000 },
    { name:"达米安·赫斯特 蝴蝶 画作",           brand:"达米安·赫斯特",category:"画作", price:2800000 },
    { name:"朱德群 抽象 油画 小尺寸",            brand:"朱德群",   category:"画作", price:1800000 },
    { name:"罗中立 父亲 版画 限量",              brand:"罗中立",   category:"画作", price:280000 },
    { name:"冷军 超写实 油画 小尺寸",            brand:"冷军",     category:"画作", price:800000 },
    { name:"曾梵志 面具 系列 油画",              brand:"曾梵志",   category:"画作", price:15000000 },
    { name:"张晓刚 血缘 系列 油画",              brand:"张晓刚",   category:"画作", price:8000000 },
    { name:"刘野 小女孩 油画",                   brand:"刘野",     category:"画作", price:2000000 },
    { name:"周春芽 桃花 系列 油画",              brand:"周春芽",   category:"画作", price:4500000 },
    { name:"萨尔瓦多·达利 版画 限量签名",       brand:"达利",     category:"画作", price:1800000 },
    { name:"马克·夏加尔 版画 限量",             brand:"夏加尔",   category:"画作", price:1500000 },
    { name:"胡安·米罗 版画 限量",               brand:"米罗",     category:"画作", price:1200000 },
    { name:"大卫·霍克尼 泳池 版画 限量",        brand:"霍克尼",   category:"画作", price:900000 },
    { name:"名酒 罗曼尼康帝 1985 750ml",         brand:"罗曼尼康帝",category:"收藏品", price:600000 },
    { name:"名酒 罗曼尼康帝 2005 750ml",         brand:"罗曼尼康帝",category:"收藏品", price:450000 },
    { name:"名酒 拉菲古堡 1982 750ml",           brand:"拉菲",     category:"收藏品", price:250000 },
    { name:"名酒 柏图斯 1990 750ml",             brand:"柏图斯",   category:"收藏品", price:350000 },
    { name:"威士忌 麦卡伦 60年 1926 限量",       brand:"麦卡伦",   category:"收藏品", price:5000000 },
    { name:"威士忌 山崎 55年 限量",              brand:"山崎",     category:"收藏品", price:8000000 },
    { name:"雪茄 高希霸 Behike 56 25支装",       brand:"高希霸",   category:"收藏品", price:30000 },
    { name:"雪茄 蒙特 85周年 限量",              brand:"蒙特",     category:"收藏品", price:25000 },
    { name:"雪茄 帕特加斯 卢西塔尼亚 25支",      brand:"帕特加斯", category:"收藏品", price:28000 },
    { name:"香水 娇兰 限量 定制款",              brand:"娇兰",     category:"收藏品", price:15000 },
    { name:"香水 迪奥 限量 收藏瓶",              brand:"迪奥",     category:"收藏品", price:12000 },
    { name:"乐高 泰坦尼克号 10294 限量",         brand:"乐高",     category:"收藏品", price:6000 },
    { name:"乐高 星球大战 千年隼 75192",         brand:"乐高",     category:"收藏品", price:8000 },
    { name:"手办 初音未来 1/1 等身 限量",        brand:"初音未来", category:"收藏品", price:300000 },
    { name:"手办 EVA 初号机 1/2 等身 限量",      brand:"EVA",      category:"收藏品", price:500000 },
    { name:"变形金刚 初版 G1 未拆封 收藏",       brand:"孩之宝",   category:"收藏品", price:150000 },
    { name:"宝可梦 皮卡丘 首版 卡牌 评级10",     brand:"宝可梦",   category:"收藏品", price:280000 },
    { name:"宝可梦 喷火龙 首版 卡牌 评级",       brand:"宝可梦",   category:"收藏品", price:180000 },
    { name:"万智牌 黑莲花 收藏 评级",            brand:"万智牌",   category:"收藏品", price:2500000 },
    { name:"邮票 大龙邮票 全套 收藏",            brand:"中国邮政", category:"收藏品", price:800000 },
    { name:"邮票 猴票 80版 四方连 收藏",         brand:"中国邮政", category:"收藏品", price:120000 },
    { name:"古钱币 光绪元宝 龙洋 收藏",          brand:"古钱币",   category:"收藏品", price:80000 },
    { name:"和田玉 羊脂玉 手镯 收藏",            brand:"和田玉",   category:"收藏品", price:1500000 },
    { name:"翡翠 帝王绿 蛋面 戒指 收藏",         brand:"翡翠",     category:"收藏品", price:5000000 },
    { name:"翡翠 冰种 手镯 收藏",                brand:"翡翠",     category:"收藏品", price:800000 },
    { name:"玛瑙 南红 手串 收藏",                brand:"南红",     category:"收藏品", price:80000 },
    { name:"蜜蜡 老蜜蜡 手串 收藏",              brand:"蜜蜡",     category:"收藏品", price:120000 },
    { name:"沉香 奇楠 手串 收藏",                brand:"沉香",     category:"收藏品", price:200000 },
    { name:"紫砂壶 顾景舟 石瓢 真品",            brand:"顾景舟",   category:"收藏品", price:1500000 },
    { name:"紫砂壶 时大彬 如意 真品",            brand:"时大彬",   category:"收藏品", price:3000000 },
    { name:"青花瓷 元青花 龙纹 梅瓶 真品",       brand:"元青花",   category:"收藏品", price:12000000 },
    { name:"青花瓷 明永乐 青花 缠枝 真品",       brand:"明永乐",   category:"收藏品", price:8000000 },
    { name:"瓷器 清乾隆 粉彩 真品",              brand:"清乾隆",   category:"收藏品", price:5000000 },
    { name:"青铜器 商周 兽面纹 尊 真品",         brand:"商周",     category:"收藏品", price:15000000 },
    { name:"佛像 鎏金 释迦牟尼 坐像 明清",       brand:"鎏金",     category:"收藏品", price:3500000 },
    { name:"古玉 汉代 玉璧 真品",                brand:"汉代玉",   category:"收藏品", price:800000 },
    { name:"手表 劳力士 中古 古劳 收藏",         brand:"劳力士",   category:"收藏品", price:250000 },
    { name:"赛车 法拉利 F2004 模型 1:8 限量",    brand:"法拉利",   category:"收藏品", price:150000 },
    { name:"钢琴 施坦威 限量 三角钢琴",          brand:"施坦威",   category:"收藏品", price:2000000 },
    { name:"吉他 马丁 D45 收藏级",               brand:"马丁",     category:"收藏品", price:280000 },
    { name:"小提琴 瓜奈利 复制品 收藏级",        brand:"瓜奈利",   category:"收藏品", price:800000 },
    { name:"相机 徕卡 M6 钛金 限量",             brand:"徕卡",     category:"收藏品", price:180000 },
    { name:"相机 哈苏 905SWC 收藏",              brand:"哈苏",     category:"收藏品", price:120000 },
    { name:"钢笔 万宝龙 888 限量",               brand:"万宝龙",   category:"收藏品", price:150000 },
    { name:"钢笔 万宝龙 星际行者 钻石",          brand:"万宝龙",   category:"收藏品", price:280000 },
    { name:"雪茄柜 高端定制 温控 收藏",          brand:"定制",     category:"收藏品", price:250000 },
    { name:"酒柜 红酒 恒温 藏酒柜",              brand:"定制",     category:"收藏品", price:120000 },
    { name:"运动卡 梅西 签字卡 限量",            brand:"梅西",     category:"收藏品", price:800000 },
    { name:"运动卡 乔丹 Rookie 卡 评级",         brand:"乔丹",     category:"收藏品", price:2500000 },
    { name:"签名 球衣 乔丹 亲签 收藏",           brand:"乔丹",     category:"收藏品", price:1500000 },
    { name:"签名 球衣 科比 亲签 收藏",           brand:"科比",     category:"收藏品", price:1200000 },
    { name:"签名 球鞋 乔丹 AJ1 亲签 收藏",       brand:"乔丹",     category:"收藏品", price:2800000 },
    { name:"乐器 古琴 唐宋 真品",                brand:"古琴",     category:"收藏品", price:12000000 },
    { name:"围棋 天然玛瑙 黑白子 收藏",          brand:"围棋",     category:"收藏品", price:150000 },
    { name:"香炉 明代 铜鎏金 香炉 真品",         brand:"明代",     category:"收藏品", price:500000 },
    { name:"茶具 建盏 曜变 真品",                brand:"建盏",     category:"收藏品", price:8000000 },
    { name:"茶具 紫砂 供春 真品",                brand:"供春",     category:"收藏品", price:2500000 },
    { name:"雪茄盒 古巴 雪松木 手工 收藏",       brand:"古巴",     category:"收藏品", price:45000 },

    /* —— 飞机/游艇（顶级资产） —— */
    { name:"塞斯纳 172 天鹰 私人飞机",           brand:"塞斯纳",   category:"飞机", price:4000000 },
    { name:"钻石 DA62 七座 螺旋桨",              brand:"钻石",     category:"飞机", price:12000000 },
    { name:"皮拉图斯 PC-12 NG 商务机",           brand:"皮拉图斯", category:"飞机", price:45000000 },
    { name:"豪客比奇 国王350i",                  brand:"豪客比奇", category:"飞机", price:55000000 },
    { name:"达索 猎鹰 2000LXS",                  brand:"达索",     category:"飞机", price:300000000 },
    { name:"达索 猎鹰 8X",                       brand:"达索",     category:"飞机", price:420000000 },
    { name:"湾流 G280",                         brand:"湾流",     category:"飞机", price:200000000 },
    { name:"湾流 G550",                         brand:"湾流",     category:"飞机", price:380000000 },
    { name:"湾流 G650ER",                       brand:"湾流",     category:"飞机", price:550000000 },
    { name:"庞巴迪 挑战者 350",                  brand:"庞巴迪",   category:"飞机", price:280000000 },
    { name:"庞巴迪 环球 6000",                   brand:"庞巴迪",   category:"飞机", price:450000000 },
    { name:"庞巴迪 环球 7500",                   brand:"庞巴迪",   category:"飞机", price:700000000 },
    { name:"空客 ACJ320neo",                     brand:"空客",     category:"飞机", price:900000000 },
    { name:"波音 BBJ 787-8",                     brand:"波音",     category:"飞机", price:1200000000 },
    { name:"罗宾逊 R44 直升机",                  brand:"罗宾逊",   category:"飞机", price:6000000 },
    { name:"贝尔 429 直升机",                    brand:"贝尔",     category:"飞机", price:45000000 },
    { name:"阿古斯塔 139 直升机",                brand:"阿古斯塔", category:"飞机", price:80000000 },
    { name:"空客 H145 直升机",                   brand:"空客",     category:"飞机", price:60000000 },
    { name:"游艇 丽娃 Aquariva 33",              brand:"丽娃",     category:"游艇", price:15000000 },
    { name:"游艇 圣汐 Predator 68",              brand:"圣汐",     category:"游艇", price:35000000 },
    { name:"游艇 公主 62 飞桥游艇",              brand:"公主",     category:"游艇", price:40000000 },
    { name:"游艇 法拉帝 780 飞桥",               brand:"法拉帝",   category:"游艇", price:70000000 },
    { name:"游艇 阿兹慕 60 飞桥",                brand:"阿兹慕",   category:"游艇", price:55000000 },
    { name:"游艇 丽娃 88' 旗舰",                 brand:"丽娃",     category:"游艇", price:150000000 },
    { name:"游艇 斐帝星 100米 超级游艇",         brand:"斐帝星",   category:"游艇", price:2500000000 },
    { name:"游艇 贝尼蒂 60米 超级游艇",          brand:"贝尼蒂",   category:"游艇", price:1500000000 },
    { name:"游艇 乐顺 80米 超级游艇",            brand:"乐顺",     category:"游艇", price:2000000000 },
    { name:"私人飞机 波音 BBJ 747-8 定制",       brand:"波音",     category:"飞机", price:3000000000 },
  ],
};
